#if !defined(AFX_IUNKNOWNVECTOR_H__B40D98C2_3CFA_11D6_8266_0050DAD4FF55__INCLUDED_)
#define AFX_IUNKNOWNVECTOR_H__B40D98C2_3CFA_11D6_8266_0050DAD4FF55__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIUnknownVector wrapper class

class CIUnknownVector : public COleDispatchDriver
{
public:
	CIUnknownVector() {}		// Calls COleDispatchDriver default constructor
	CIUnknownVector(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CIUnknownVector(const CIUnknownVector& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long size();
	LPUNKNOWN at(long lPos);
	void push_back(LPUNKNOWN pObj);
	void clear();
	LPUNKNOWN front();
	LPUNKNOWN back();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IUNKNOWNVECTOR_H__B40D98C2_3CFA_11D6_8266_0050DAD4FF55__INCLUDED_)
