//==================================================================================================
//
// COPYRIGHT (c) 2000 UCLID SOFTWARE, LLC., IN PUBLISHED AND UNPUBLISHED WORKS
// ALL RIGHTS RESERVED.
//
// FILE:	Picture.h
//
// PURPOSE:	This is an header file for CPicture class
//			where this has been derived from the COleDispatchDriver()
//			class.  The code written in this file makes it possible for
//			initialize to set the view.
// NOTES:	
//
// AUTHORS:	
//
//==================================================================================================

#if !defined(AFX_PICTURE_H__E3584D23_F085_11D3_B251_008048E6E7FE__INCLUDED_)
#define AFX_PICTURE_H__E3584D23_F085_11D3_B251_008048E6E7FE__INCLUDED_

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

//==================================================================================================
// COPYRIGHT (c) 2000 UCLID SOFTWARE, LLC., IN PUBLISHED AND UNPUBLISHED WORKS
// ALL RIGHTS RESERVED.
// CLASS:	CPicture
//
// PURPOSE:	
//			Ole class for the Wang control generated by framework 
//			It Will not be edited

// REQUIRE:	None
// 
// INVARIANTS: None

// EXTENSIONS:None

// NOTES:	None
//
//==================================================================================================

class CPicture : public COleDispatchDriver
{
public:
	CPicture() {}		// Calls COleDispatchDriver default constructor
	CPicture(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPicture(const CPicture& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetHandle();
	long GetHPal();
	void SetHPal(long);
	short GetType();
	long GetWidth();
	long GetHeight();

// Operations
public:
	// method 'Render' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PICTURE_H__E3584D23_F085_11D3_B251_008048E6E7FE__INCLUDED_)
