//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extract.FileActionManager.Database {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class LicenseContact : global::System.Configuration.ApplicationSettingsBase {
        
        private static LicenseContact defaultInstance = ((LicenseContact)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LicenseContact())));
        
        public static LicenseContact Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendAlertsToExtract {
            get {
                return ((bool)(this["SendAlertsToExtract"]));
            }
            set {
                this["SendAlertsToExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendAlertsToSpecified {
            get {
                return ((bool)(this["SendAlertsToSpecified"]));
            }
            set {
                this["SendAlertsToSpecified"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpecifiedAlertRecipients {
            get {
                return ((string)(this["SpecifiedAlertRecipients"]));
            }
            set {
                this["SpecifiedAlertRecipients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LicenseContactOrganization {
            get {
                return ((string)(this["LicenseContactOrganization"]));
            }
            set {
                this["LicenseContactOrganization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LicenseContactEmail {
            get {
                return ((string)(this["LicenseContactEmail"]));
            }
            set {
                this["LicenseContactEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LicenseContactPhone {
            get {
                return ((string)(this["LicenseContactPhone"]));
            }
            set {
                this["LicenseContactPhone"] = value;
            }
        }
    }
}
