USE [master]
GO
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'FPDB')
BEGIN
CREATE DATABASE [FPDB] ON  PRIMARY 
( NAME = N'FPDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Data\FPDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FPDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Data\FPDB_log.LDF' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END

GO
EXEC dbo.sp_dbcmptlevel @dbname=N'FPDB', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FPDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FPDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FPDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FPDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FPDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FPDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FPDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FPDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [FPDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FPDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FPDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FPDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FPDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FPDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FPDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FPDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FPDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FPDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FPDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FPDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FPDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FPDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FPDB] SET  READ_WRITE 
GO
ALTER DATABASE [FPDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FPDB] SET  MULTI_USER 
GO
ALTER DATABASE [FPDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FPDB] SET DB_CHAINING OFF 
