#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICodeDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EngineeringLICodeDB")]
	public partial class LICodeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LICodeDBDataContext() : 
				base(global::LICodeDB.Properties.Settings.Default.EngineeringLICodeDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LICodeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LICodeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LICodeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LICodeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GetLICodesResult> GetLICodesResults
		{
			get
			{
				return this.GetTable<GetLICodesResult>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEliCodes")]
		public ISingleResult<GetLICodesResult> GetEliCodes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumberOfCodes", DbType="Int")] System.Nullable<int> numberOfCodes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numberOfCodes);
			return ((ISingleResult<GetLICodesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMliCodes")]
		public ISingleResult<GetLICodesResult> GetMliCodes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumberOfCodes", DbType="Int")] System.Nullable<int> numberOfCodes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numberOfCodes);
			return ((ISingleResult<GetLICodesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class GetLICodesResult
	{
		
		private string _LICode;
		
		public GetLICodesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LICode", DbType="nvarchar(13)", CanBeNull=false)]
		public string LICode
		{
			get
			{
				return this._LICode;
			}
			set
			{
				if ((this._LICode != value))
				{
					this._LICode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
