// SafeNetUtilsTest.idl : IDL source for SafeNetUtilsTest.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SafeNetUtilsTest.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(E201DE56-A3F4-4197-A213-43DB03E11941),
		dual,
		helpstring("ITestSafeNetUtils Interface"),
		pointer_default(unique)
	]
	interface ITestSafeNetUtils : IDispatch
	{
	};

[
	uuid(F3DA127F-D362-4AF1-A1BB-8B56179188D7),
	version(1.0),
	helpstring("SafeNetUtilsTest 1.0 Type Library")
]
library SAFENETUTILSTESTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(EBB72604-8FFB-44C3-8C7F-3EEB1C0ECFF4),
		helpstring("TestSafeNetUtils Class")
	]
	coclass TestSafeNetUtils
	{
		[default] interface ITestSafeNetUtils;
	};
};
