//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - AJUD.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - ATDE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - BLANK.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - CLUP.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - DTRU.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - GDEE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - NCOM.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - NDEF.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - NFTL.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - NSJU.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - NSTL.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - NTSA.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - QCDE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - RECO.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - REND.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - RLIE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - STRU.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - TDEE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - TTDE.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantor - Issue11.dat
