/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UsersApiTests
    {
        private UsersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UsersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UsersApi
            //Assert.IsInstanceOfType(typeof(UsersApi), instance, "instance is a UsersApi");
        }

        
        /// <summary>
        /// Test ApiUsersLoginPost
        /// </summary>
        [Test]
        public void ApiUsersLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //User user = null;
            //instance.ApiUsersLoginPost(user);
            
        }
        
        /// <summary>
        /// Test ApiUsersLogoutDelete
        /// </summary>
        [Test]
        public void ApiUsersLogoutDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //User user = null;
            //instance.ApiUsersLogoutDelete(user);
            
        }
        
        /// <summary>
        /// Test GetUserClaimsGet
        /// </summary>
        [Test]
        public void GetUserClaimsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.GetUserClaimsGet(username);
            //Assert.IsInstanceOf<List<Claim>> (response, "response is List<Claim>");
        }
        
    }

}
