/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WorkflowApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WorkflowApiTests
    {
        private WorkflowApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WorkflowApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkflowApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WorkflowApi
            //Assert.IsInstanceOfType(typeof(WorkflowApi), instance, "instance is a WorkflowApi");
        }

        
        /// <summary>
        /// Test ApiWorkflowGetDefaultWorkflowByUsernameGet
        /// </summary>
        [Test]
        public void ApiWorkflowGetDefaultWorkflowByUsernameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.ApiWorkflowGetDefaultWorkflowByUsernameGet(username);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test ApiWorkflowGetWorkflowStatusByWorkflowNameGet
        /// </summary>
        [Test]
        public void ApiWorkflowGetWorkflowStatusByWorkflowNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string workflowName = null;
            //var response = instance.ApiWorkflowGetWorkflowStatusByWorkflowNameGet(workflowName);
            //Assert.IsInstanceOf<WorkflowStatus> (response, "response is WorkflowStatus");
        }
        
        /// <summary>
        /// Test ApiWorkflowGetWorkflowsGet
        /// </summary>
        [Test]
        public void ApiWorkflowGetWorkflowsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiWorkflowGetWorkflowsGet();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test ApiWorkflowPost
        /// </summary>
        [Test]
        public void ApiWorkflowPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Workflow workflow = null;
            //instance.ApiWorkflowPost(workflow);
            
        }
        
    }

}
