// AFFileProcessors.idl : IDL source for AFFileProcessors.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (AFFileProcessors.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(0D45D3B2-CF74-4000-9549-EC5BD95B6A55),
	version(1.0),
	helpstring("AFFileProcessors 1.0 Type Library")
]
library UCLID_AFFILEPROCESSORSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	importlib("..\..\..\..\ReusableComponents\COMComponents\UCLIDCOMUtils\Core\Code\UCLIDCOMUtils.tlb");
	importlib("..\..\..\..\ReusableComponents\COMComponents\UCLIDComponentsLM\COMLM\Code\COMLM.tlb");
	importlib("..\..\..\..\ReusableComponents\COMComponents\UCLIDFileProcessing\Code\UCLIDFILEPROCESSING.tlb");

	//////////////
	// Enums
	//////////////
	typedef 
	[
		uuid(891CCDB2-84CD-4011-BEBF-1C9F89C55E75), 
		helpstring("UCLID OCR Image Pages Type")
	]
    enum
	{
		kNoOCR = 0,
		kOCRAllPages = 1,
        kOCRCertainPages = 2
    } EOCRPagesType;

	//////////////
	// Interfaces
	//////////////
	[
		object,
		uuid(06557EDF-0C1E-4A5D-8B6C-51E60860FCE7),
		dual,
		helpstring("IAFEngineFileProcessor Interface"),
		pointer_default(unique)
	]
	interface IAFEngineFileProcessor : IDispatch
	{
		// if input is an image file and its corresponding USS file exists, then read that USS file
		[propget, id(1), helpstring("property ReadUSSFile")] HRESULT ReadUSSFile([out, retval] VARIANT_BOOL *pVal);
		[propput, id(1), helpstring("property ReadUSSFile")] HRESULT ReadUSSFile([in] VARIANT_BOOL newVal);
		// if input is an image file and its corresponding USS file exists, then create the USS file 
		// and read from the USS file
		[propget, id(2), helpstring("property CreateUSSFile")] HRESULT CreateUSSFile([out, retval] VARIANT_BOOL *pVal);
		[propput, id(2), helpstring("property CreateUSSFile")] HRESULT CreateUSSFile([in] VARIANT_BOOL newVal);
		// name of the rule set file name (encrypted or not)
		[propget, id(3), helpstring("property RuleSetFileName")] HRESULT RuleSetFileName([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property RuleSetFileName")] HRESULT RuleSetFileName([in] BSTR newVal);
		// OCR all pages or only OCR specific pages or Don't OCR any pages
		[propget, id(4), helpstring("property OCRPagesType")] HRESULT OCRPagesType([out, retval] EOCRPagesType *pVal);
		[propput, id(4), helpstring("property OCRPagesType")] HRESULT OCRPagesType([in] EOCRPagesType newVal);
		// If OCRPageRange = kOCRPages, this property specifies certain page numbers in a string
		[propget, id(5), helpstring("property OCRCertainPages")] HRESULT OCRCertainPages([out, retval] BSTR *strSpecificPages);
		[propput, id(5), helpstring("property OCRCertainPages")] HRESULT OCRCertainPages([in] BSTR strSpecificPages);
		// If a cleaned image should be used for OCR (if available)
		[propget, id(6), helpstring("property UseCleanedImage")] HRESULT UseCleanedImage([out, retval] VARIANT_BOOL* pVal);
		[propput, id(6), helpstring("property UseCleanedImage")] HRESULT UseCleanedImage([in] VARIANT_BOOL newVal);
	};

	[
		object,
		uuid(F96AFDF1-0F7D-4E71-A0E8-E38FF7BBF250),
		dual,
		helpstring("IAFConvertVOAToXMLTask Interface"),
		pointer_default(unique)
	]
	interface IAFConvertVOAToXMLTask : IDispatch
	{
		[propget, id(1), helpstring("property VOAFile")] HRESULT
			VOAFile([out, retval] BSTR* pbstrVOAFile);
		[propput, id(1), helpstring("property VOAFile")] HRESULT
			VOAFile([in] BSTR bstrVOAFile);
		[propget, id(2), helpstring("property XMLOutputHandler")] HRESULT
			XMLOutputHandler([out, retval] IUnknown** ppXMLOutputHandler);
		[propput, id(2), helpstring("property XMLOutputHandler")] HRESULT
			XMLOutputHandler([in] IUnknown* pXMLOutputHandler);
	};

	//////////////
	// CoClasses
	//////////////
	[
		uuid(0F831302-E48D-4A2C-B636-485612A60262),
		helpstring("AFEngineFileProcessor Class")
	]
	coclass AFEngineFileProcessor
	{
		[default] interface IAFEngineFileProcessor;
		interface IFileProcessingTask;
		interface ICategorizedComponent;
		interface ICopyableObject;
		interface ILicensedComponent;
		interface IMustBeConfiguredObject;
	};
	[
		uuid(F0B58CEC-401F-42AC-BA0C-F11E3A3ED3F4),
		helpstring("AFEngineFileProcessorPP Class")
	]
	coclass AFEngineFileProcessorPP
	{
		interface IUnknown;
	};

	[
		uuid(23FB28AB-EE7D-4708-AA23-B3F96B0DA094),
		helpstring("AFConvertVOAToXMLTask Class")
	]
	coclass AFConvertVOAToXMLTask
	{
		[default] interface IAFConvertVOAToXMLTask;
		interface IFileProcessingTask;
		interface ICategorizedComponent;
		interface ICopyableObject;
		interface ILicensedComponent;
		interface IMustBeConfiguredObject;
	};
	[
		uuid(A7E8330B-AC29-445A-AF59-970D0EE469CA),
		helpstring("AFConvertVOAToXMLTaskPP Class")
	]
	coclass AFConvertVOAToXMLTaskPP
	{
		interface IUnknown;
	};
};
