//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AFFileProcessors.rc
//
#define IDS_PROJNAME                    100
#define IDR_AFENGINEFILEPROCESSOR       108
#define IDS_TITLEAFEngineFileProcessorPP 109
#define IDS_HELPFILEAFEngineFileProcessorPP 110
#define IDS_DOCSTRINGAFEngineFileProcessorPP 111
#define IDR_AFENGINEFILEPROCESSORPP     112
#define IDD_AFENGINEFILEPROCESSORPP     113
#define IDR_AFCONVERTVOATOXMLTASK       114
#define IDR_AFCONVERTVOATOXMLTASKPP     115
#define IDD_AFCONVERTVOATOXMLTASKPP     116
#define IDR_AFENHANCEOCRTASK			117
#define IDR_AFENHANCEOCRTASKPP			118
#define IDI_ICON_INFO                   201
#define IDC_OUTPUT_IMAGE_NAME           202
#define IDC_RULE_FILE                   203
#define IDC_BTN_SELECT_OUTPUT_TAG       204
#define IDC_BTN_SELECT_RULE_TAG         205
#define IDC_OUTPUT_IMAGE_HELP           206
#define IDC_EDIT_RULE_FILE              208
#define IDC_BTN_BROWSE_AFE              209
#define IDC_CHK_SAVE_RESULTS            210
#define IDC_CHK_FROM_USS                211
#define IDC_BTN_RULEFILE_BROWSE         212
#define IDC_RADIO_OCR_ALL               213
#define IDC_RADIO_OCR_SPECIFIED         214
#define IDC_EDIT_PAGES                  215
#define IDI_ICON_SELECT_DOC_TAG         217
#define IDC_EDIT_INPUT_VOA_FILE         218
#define IDC_BTN_VOA_FILE_DOC_TAGS       219
#define IDC_BTN_BROWSE_VOA_FILE         220
#define IDC_EDIT_OUTPUT_XML_FILE        221
#define IDC_BTN_XML_FILE_DOC_TAGS       222
#define IDC_BTN_BROWSE_XML_FILE         223
#define IDC_BTN_CONFIGURE_XML_OUTPUT    224
#define IDC_BTN_DOCTAGS_AFE             225
#define IDC_RADIO_OCR_NONE              226
#define IDC_CHK_USE_CLEAN_IMAGE         227
#define IDC_CHK_PROVIDE_INPUT           228
#define IDC_EDIT_INPUT_DATA             229
#define IDC_BTN_DOCTAGS_DATA_INPUT      230
#define IDC_BTN_BROWSE_DATA_INPUT       231
#define IDD_ENHANCEOCRTASKPP            232
#define IDC_RADIO_GENERAL_FILTERS       233
#define IDC_FILTER_LEVEL                234
#define IDC_RADIO_HALFTONE_FILTERS      235
#define IDC_RADIO_ALIASED_FILTERS       236
#define IDC_RADIO_SMUDGED_FILTERS       237
#define IDC_RADIO_CUSTOM_FILTERS        238
#define IDC_EDIT_CUSTOM_FILTERS         239
#define IDC_BTN_CUSTOM_FILTERS_DOC_TAG  240
#define IDC_BTN_CUSTOM_FILTERS_BROWSE   241
#define IDC_EDIT_PREFERRED_FORMAT       242
#define IDC_EDIT_CHARS_TO_IGNORE        243
#define IDC_BTN_PREFERRED_FORMAT_DOC_TAG 244
#define IDC_CHK_OUTPUT_FILTERED_IMAGES  245
#define IDC_EDIT_CONFIDENCE_CRITERIA    246
#define IDC_STATIC_FILTER_LABEL1        247
#define IDC_STATIC_FILTER_LABEL2        248
#define IDC_STATIC_FILTER_LABEL3        249
#define IDC_PREFERRED_REGEX_INFO        253
#define IDC_BTN_PREFERRED_FORMAT_BROWSE 254
#define IDB_BITMAP_HALFTONE_SPECKLED    255
#define IDB_BITMAP_ALIASED_DIFFUSE      256
#define IDB_BITMAP_SMUDGED              257

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         258
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
