UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Affidavit_Misc.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Affidavit_Misc.Affidavit_Heirship.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Affidavit_of_Death.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Agreement_Misc.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Assignment_of_Mortgage.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Assignment_of_Rents.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Contract_Misc.Land_Contract.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Deed_Misc.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Discharge_from_Active_Duty.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Easement_Misc.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Lien_Misc.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Mechanics_Lien.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Modification_of_Deed_of_Trust.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Mortgage_Deed_of_Trust.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Notice_of_Federal_Tax_Lien.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Notice_of_Hearing.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Power_of_Attorney.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Quit_Claim_Deed.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Release_of_Assignment_of_Rents.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Release_of_Federal_Tax_Lien.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Release_of_Mechanics_Lien.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Satisfaction_of_Judgment.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Satisfaction_of_Mortgage.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Sewer_Lien.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Sheriffs_Deed.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Storm_Sewer_Lien.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Subordination_Agreement.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Substitution_of_Trustee.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Unclassified.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;IN - Madison - CSI - Warranty_Deed.dat
