// AFDataScorers.idl : IDL source for AFDataScorers.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (AFDataScorers.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(F0A8FC59-37EE-4EB5-A9C8-C322F851BC88),
	version(1.0),
	helpstring("UCLID AFDataScorers 1.0 Type Library")
]
library UCLID_AFDATASCORERSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	importlib("..\..\..\..\ReusableComponents\COMComponents\UCLIDCOMUtils\Core\Code\UCLIDCOMUtils.tlb");
	importlib("..\..\..\..\ReusableComponents\COMComponents\UCLIDComponentsLM\COMLM\Code\COMLM.tlb");
	importlib("..\..\AFCore\Code\AFCore.tlb");


	//////////////
	// Enums
	//////////////
	[
		object,
		uuid(0EDBFC88-9CBE-4F4B-9458-55E94E991A50),
		dual,
		helpstring("IEntityNameDataScorer Interface"),
		pointer_default(unique)
	]
	interface IEntityNameDataScorer : IDispatch
	{
	};

	[
		object,
		uuid(D43B269D-1ECD-4984-912C-D0FD58BE3176),
		dual,
		nonextensible,
		helpstring("ICharacterConfidenceDS Interface"),
		pointer_default(unique)
	]
	interface ICharacterConfidenceDS : IDispatch{
		//------------------------------------------------------------------------------------------
		// PURPOSE: Property that indicates how to select the character confidence 
		[propget, id(1), helpstring("property AggregateFunction")] 
		HRESULT AggregateFunction([out, retval] EAggregateFunctions *pVal);
		[propput, id(1), helpstring("property UCLID_COMUTILSLib::AggregateFunction")] 
			HRESULT AggregateFunction([in] EAggregateFunctions newVal);
	};

	[
		uuid(0E9555F7-9F77-41BD-9762-199F07A871E0),
		helpstring("EntityNameDataScorer Class")
	]
	coclass EntityNameDataScorer
	{
		[default] interface IDataScorer;
		interface ILicensedComponent;
	};
	[
		uuid(07F86A2E-923C-4EDF-9E6E-17588E745324),
		helpstring("CharacterConfidenceDS Class")
	]
	coclass CharacterConfidenceDS
	{
		[default] interface ICharacterConfidenceDS;
		interface IDataScorer;
		interface ICategorizedComponent;
		interface ICopyableObject;
		interface ILicensedComponent;
		interface IMustBeConfiguredObject;
	};
	[
		uuid(83EFE042-EB4B-4C8E-BCAD-EE7689D07088),
		helpstring("CharacterConfidenceDSPP Class")
	]
	coclass CharacterConfidenceDSPP
	{
		[default] interface IUnknown;
	};
};
