//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ESImageCleanup.rc
//
#define IDS_PROJNAME                    100
#define IDR_ESIMAGECLEANUP              101
#define IDR_IMAGECLEANUPOPERATION       103
#define IDR_REMOVEHALFTONESICO          104
#define IDR_IMAGECLEANUPSETTINGS        105
#define IDR_IMAGECLEANUPENGINE          106
#define IDR_DESPECKLEICO                107
#define IDR_DESPECKLEICOPP              108
#define IDD_DESPECKLEICOPP              109
#define IDS_DOCSTRINGDESPECKLEICOPP     110
#define IDS_HELPFILEDESPECKLEICOPP      111
#define IDS_TITLEDESPECKLEICOPP         112
#define IDR_DELETELINESANDREPAIRICO     113
#define IDR_DELETELINESANDREPAIRICOPP   114
#define IDD_DELETELINESANDREPAIRICOPP   115
#define IDS_DOCSTRINGDELETELINESANDREPAIRICOPP 116
#define IDS_HELPFILEDELETELINESANDREPAIRICOPP 117
#define IDS_TITLEDELETELINESANDREPAIRICOPP 118
#define IDR_CLEANIMAGEBORDERSICO        119
#define IDR_SMOOTHCHARACTERSICO         120
#define IDR_SMOOTHCHARACTERSICOPP       121
#define IDD_SMOOTHCHARACTERSICOPP       122
#define IDS_DOCSTRINGSMOOTHCHARACTERSICOPP 123
#define IDS_HELPFILESMOOTHCHARACTERSICOPP 124
#define IDS_TITLESMOOTHCHARACTERSICOPP  125
#define IDR_FILLSTRIPESICO				126
#define IDC_EDIT_DESPECKLE_SIZE         201
#define IDC_EDIT_DELETELINES_LENGTH     202
#define IDC_EDIT_DELETELINES_GAP        203
#define IDC_RADIO_DELETELINESANDREPAIR_VERT 204
#define IDC_RADIO_DELETELINESANDREPAIR_HORZ 205
#define IDC_RADIO_DELETELINESANDREPAIR_BOTH 206
#define IDC_RADIO_SMOOTHCHARACTERS_LIGHTEN 207
#define IDC_RADIO_SMOOTHCHARACTERS_DARKEN 208
#define IDD_SMOOTHCHARACTERSICO         209

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         209
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
