//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AFSelectors.rc
//
#define IDS_PROJNAME                    100
#define IDR_AFSELECTORS                 101
#define IDR_QUERYBASEDAS                103
#define IDR_SPATIALCONTENTBASEDAS       104
#define IDD_QUERYBASEDASPP              105
#define IDS_TITLEQUERYBASEDASPP         106
#define IDS_HELPFILEQUERYBASEDASPP      107
#define IDS_DOCSTRINGQUERYBASEDASPP     108
#define IDR_QUERYBASEDASPP              109
#define IDD_SPATIALCONTENTBASEDASPP     110
#define IDS_TITLESPATIALCONTENTBASEDASPP 111
#define IDS_HELPFILESPATIALCONTENTBASEDASPP 112
#define IDS_DOCSTRINGSPATIALCONTENTBASEDASPP 113
#define IDR_SPATIALCONTENTBASEDASPP     114
#define IDR_SPATIALPROXIMITYAS          115
#define IDD_SPATIALPROXIMITYASPP        116
#define IDR_SPATIALPROXIMITYASPP        117
#define IDC_COMBO_CONTAINS              201
#define IDC_EDIT_PIXEL_ROWS             202
#define IDC_EDIT_MIN_PERCENT            203
#define IDC_EDIT_MAX_PERCENT            204
#define IDC_CHECK_INCLUDE_NONSPATIAL    205
#define IDC_EDIT_QUERY                  206
#define IDC_CHECK_INCLUDE_DEBUG_ATTRIBUTES 207
#define IDC_EDIT_TARGET_QUERY           208
#define IDC_EDIT_REFERENCE_QUERY        209
#define IDC_RADIO_SEPARATE_LINES        210
#define IDC_RADIO_OVERALL_BOUNDS        211
#define IDC_COMBO_BORDER_LEFT           212
#define IDC_COMBO_BORDER_TOP            213
#define IDC_COMBO_BORDER_RIGHT          214
#define IDC_COMBO_BORDER_BOTTOM         215
#define IDC_EDIT_EXPAND_AMOUNT_LEFT     216
#define IDC_EDIT_EXPAND_AMOUNT_TOP      217
#define IDC_EDIT_EXPAND_AMOUNT_RIGHT    218
#define IDC_EDIT_EXPAND_AMOUNT_BOTTOM   219
#define IDC_COMBO_REFERENCE_LEFT        220
#define IDC_COMBO_REFERENCE_TOP         221
#define IDC_COMBO_REFERENCE_RIGHT       222
#define IDC_COMBO_REFERENCE_BOTTOM      223
#define IDC_COMBO_EXPAND_DIR_LEFT       224
#define IDC_COMBO_EXPAND_DIR_TOP        225
#define IDC_COMBO_EXPAND_DIR_RIGHT      226
#define IDC_COMBO_EXPAND_DIR_BOTTOM     227
#define IDC_COMBO_EXPAND_UNITS_TOP      228
#define IDC_COMBO_EXPAND_UNITS_LEFT     229
#define IDC_COMBO_EXPAND_UNITS_RIGHT    230
#define IDC_COMBO_EXPAND_UNITS_BOTTOM   231
#define IDC_COMBO_INCLUSION_METHOD      232

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        233
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         233
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
