UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - AJUD.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - ATDE.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - BLANK.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - CLUP.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - DTRU.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - GDEE.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - NCOM.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - NDEF.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - NFTL.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - NSJU.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - NSTL.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - NTSA.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - QCDE.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - RECO.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - REND.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - RLIE.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - STRU.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - TDEE.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Grantee - TTDE.dat
