UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - AFF_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - AFF_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - DC_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - DC_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - DEED_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - DEED_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - DMTG_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - DMTG_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - IRS_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - IRS_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - LC_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - LC_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - LP_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - LP_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - MITL_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - MITL_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - MTG_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - MTG_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - OGLEASE_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - PA116_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - QC_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - QC_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - SURVEY_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - WD_Set002.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee - WD_Set003.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Bay - FNTI - GrantorGrantee.dat
