/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DocumentAttribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentAttributeTests
    {
        // TODO uncomment below to declare an instance variable for DocumentAttribute
        //private DocumentAttribute instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentAttribute
            //instance = new DocumentAttribute();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentAttribute
        /// </summary>
        [Test]
        public void DocumentAttributeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentAttribute
            //Assert.IsInstanceOfType<DocumentAttribute> (instance, "variable 'instance' is a DocumentAttribute");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AverageCharacterConfidence'
        /// </summary>
        [Test]
        public void AverageCharacterConfidenceTest()
        {
            // TODO unit test for the property 'AverageCharacterConfidence'
        }
        /// <summary>
        /// Test the property 'ConfidenceLevel'
        /// </summary>
        [Test]
        public void ConfidenceLevelTest()
        {
            // TODO unit test for the property 'ConfidenceLevel'
        }
        /// <summary>
        /// Test the property 'HasPositionInfo'
        /// </summary>
        [Test]
        public void HasPositionInfoTest()
        {
            // TODO unit test for the property 'HasPositionInfo'
        }
        /// <summary>
        /// Test the property 'SpatialPosition'
        /// </summary>
        [Test]
        public void SpatialPositionTest()
        {
            // TODO unit test for the property 'SpatialPosition'
        }
        /// <summary>
        /// Test the property 'ChildAttributes'
        /// </summary>
        [Test]
        public void ChildAttributesTest()
        {
            // TODO unit test for the property 'ChildAttributes'
        }

    }

}
