/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ErrorInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorInfoTests
    {
        // TODO uncomment below to declare an instance variable for ErrorInfo
        //private ErrorInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorInfo
            //instance = new ErrorInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorInfo
        /// </summary>
        [Test]
        public void ErrorInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorInfo
            //Assert.IsInstanceOfType<ErrorInfo> (instance, "variable 'instance' is a ErrorInfo");
        }

        /// <summary>
        /// Test the property 'ErrorOccurred'
        /// </summary>
        [Test]
        public void ErrorOccurredTest()
        {
            // TODO unit test for the property 'ErrorOccurred'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
