/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProcessingStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessingStatusTests
    {
        // TODO uncomment below to declare an instance variable for ProcessingStatus
        //private ProcessingStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessingStatus
            //instance = new ProcessingStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessingStatus
        /// </summary>
        [Test]
        public void ProcessingStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessingStatus
            //Assert.IsInstanceOfType<ProcessingStatus> (instance, "variable 'instance' is a ProcessingStatus");
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'DocumentStatus'
        /// </summary>
        [Test]
        public void DocumentStatusTest()
        {
            // TODO unit test for the property 'DocumentStatus'
        }

    }

}
