/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SpatialLineBounds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpatialLineBoundsTests
    {
        // TODO uncomment below to declare an instance variable for SpatialLineBounds
        //private SpatialLineBounds instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpatialLineBounds
            //instance = new SpatialLineBounds();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpatialLineBounds
        /// </summary>
        [Test]
        public void SpatialLineBoundsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpatialLineBounds
            //Assert.IsInstanceOfType<SpatialLineBounds> (instance, "variable 'instance' is a SpatialLineBounds");
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Test]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Top'
        /// </summary>
        [Test]
        public void TopTest()
        {
            // TODO unit test for the property 'Top'
        }
        /// <summary>
        /// Test the property 'Left'
        /// </summary>
        [Test]
        public void LeftTest()
        {
            // TODO unit test for the property 'Left'
        }
        /// <summary>
        /// Test the property 'Botton'
        /// </summary>
        [Test]
        public void BottonTest()
        {
            // TODO unit test for the property 'Botton'
        }
        /// <summary>
        /// Test the property 'Right'
        /// </summary>
        [Test]
        public void RightTest()
        {
            // TODO unit test for the property 'Right'
        }

    }

}
