<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="/">
  <html>
    <head>
      <link REL="StyleSheet" HREF="IDShieldReportStyles.css" TYPE="text/css"/>
    </head>
    <body>
      <table border="1" cellspacing="0" width="100%">
        <tr class="header">
          <td align="center">
            <br/>Extract Systems ID Shield Report<br/><br/>
          </td>
        </tr>
      </table>
      <br/>
      <table border="1" cellspacing="0" width="60%">
        <tr class="header">
          <td align="left" colspan="3">Report information</td>
        </tr>
        <tr class="rowColor1">
          <td>Database server : </td>
          <td><xsl:value-of select="IDShieldVerificationReport/ReportInfo/DBServerName"/></td>
        </tr>
        <tr class="rowColor2">
          <td>Database name : </td>
          <td><xsl:value-of select="IDShieldVerificationReport/ReportInfo/DBName"/></td>
        </tr>
        <tr class="rowColor1">
          <td align="left">Generated by : </td>
          <td><xsl:value-of select="IDShieldVerificationReport/ReportInfo/GeneratedBy"/></td>
        </tr>
        <tr class="rowColor2">
          <td align="left">Generated on : </td>
          <td><xsl:value-of select="IDShieldVerificationReport/ReportInfo/GeneratedOn"/></td>
        </tr>
      </table>
      <br/>
      <table border="1" cellspacing="0" width="100%">
        <tr class="header">
          <td colspan="1">Project information</td>
          <td colspan="2">Documents</td>
          <td colspan="2">Pages contained</td>
        </tr>
        <tr class="rowColor1">
          <td>Total documents in project : </td>
          <td colspan="2">
            <xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalDocsInProject, '###,###,###')"/>
          </td>
          <td colspan="2">
            <xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalPagesInProject, '###,###,###')"/>
          </td>
        </tr>
        <tr class="rowColor2">
          <td>Total documents verified : </td>
          <!-- Total documents verified -->
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalDocsVerified = 0">
            <td class="leftOfMergedCell">0</td>
            <td class="rightOfMergedCell">(0%)</td>
          </xsl:if>
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalDocsVerified != 0">
            <td class="leftOfMergedCell">
                <xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalDocsVerified, '###,###,###')"/>
            </td>
            <td class="rightOfMergedCell">
                (<xsl:value-of select="format-number(round(IDShieldVerificationReport/ProjectInfo/TotalDocsVerified * 100 div IDShieldVerificationReport/ProjectInfo/TotalDocsInProject), '###,###,###')"/>%)
            </td>
          </xsl:if>
          <!-- Total pages verified -->
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedDocs = 0">
            <td class="leftOfMergedCell">0</td>
            <td class="rightOfMergedCell">(0%)</td>
          </xsl:if>
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedDocs != 0">
            <td class="leftOfMergedCell">
              <xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedDocs, '###,###,###')"/>
            </td>
            <td class="rightOfMergedCell">
              (<xsl:value-of select="format-number(round(IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedDocs * 100 div IDShieldVerificationReport/ProjectInfo/TotalPagesInProject), '###,###,###')"/>%)
            </td>
          </xsl:if>
        </tr>
        <tr class="rowColor1">
          <td>Total documents redacted : </td>
          <!-- Total documents redacted -->
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalDocsRedacted = 0">
            <td class="leftOfMergedCell">0</td>
            <td class="rightOfMergedCell">(0%)</td>
          </xsl:if>
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalDocsRedacted != 0">
			<td class="leftOfMergedCell">
            <xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalDocsRedacted, '###,###,###')"/>
			</td>
			<td class="rightOfMergedCell">
				(<xsl:value-of select="format-number(round(IDShieldVerificationReport/ProjectInfo/TotalDocsRedacted * 100 div IDShieldVerificationReport/ProjectInfo/TotalDocsInProject), '###,###,###')"/>%)
			</td>
		  </xsl:if>
          <!-- Total pages redacted -->
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalPagesInRedactedDocs = 0">
            <td class="leftOfMergedCell">0</td>
            <td class="rightOfMergedCell">(0%)</td>
          </xsl:if>
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalPagesInRedactedDocs != 0">
			<td class="leftOfMergedCell">
				<xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalPagesInRedactedDocs, '###,###,###')"/>
			</td>
			<td class="rightOfMergedCell">
				(<xsl:value-of select="format-number(round(IDShieldVerificationReport/ProjectInfo/TotalPagesInRedactedDocs * 100 div IDShieldVerificationReport/ProjectInfo/TotalPagesInProject), '###,###,###')"/>%)
			</td>
		  </xsl:if>
        </tr>
        <tr class="rowColor2">
          <td>Total documents verified but not redacted : </td>
          <!-- Total documents verified but not redacted -->
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalDocsVerifiedNotRedacted = 0">
            <td class="leftOfMergedCell">0</td>
            <td class="rightOfMergedCell">(0%)</td>
          </xsl:if>
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalDocsVerifiedNotRedacted != 0">
            <td class="leftOfMergedCell">
              <xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalDocsVerifiedNotRedacted, '###,###,###')"/>
            </td>
            <td class="rightOfMergedCell">
              (<xsl:value-of select="format-number(round(IDShieldVerificationReport/ProjectInfo/TotalDocsVerifiedNotRedacted * 100 div IDShieldVerificationReport/ProjectInfo/TotalDocsInProject), '###,###,###')"/>%)
            </td>
          </xsl:if>
          <!-- Total pages verified but not redacted -->
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedNotRedactedDocs = 0">
            <td class="leftOfMergedCell">0</td>
            <td class="rightOfMergedCell">(0%)</td>
          </xsl:if>
          <xsl:if test="IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedNotRedactedDocs != 0">
            <td class="leftOfMergedCell">
              <xsl:value-of select="format-number(IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedNotRedactedDocs, '###,###,###')"/>
            </td>
            <td class="rightOfMergedCell">
              (<xsl:value-of select="format-number(round(IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedNotRedactedDocs * 100 div IDShieldVerificationReport/ProjectInfo/TotalPagesInProject), '###,###,###')"/>%)
            </td>
          </xsl:if>
        </tr>
      </table>
      <br/>
      <xsl:if test="IDShieldVerificationReport/VerifierInfo != 0">
        <table border="1" width="100%" cellspacing="0" cellpadding="3">
          <tr class="header">
            <td>Verification information</td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td align="left" colspan="2">
                <xsl:value-of select="@Name"/>
              </td>
            </xsl:for-each>
            <td>Total</td>
          </tr>
          <tr class="rowColor1">
            <td># documents verified : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td class="leftOfMergedCell" align="left">
                <xsl:value-of select="format-number(TotalDocsVerified, '###,###,###')"/>
              </td>
              <td class="rightOfMergedCell" align="left">
                (<xsl:value-of select="format-number(round(TotalDocsVerified * 100 div sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalDocsVerified)), '###,###,###')"/>%)
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="format-number(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalDocsVerified), '###,###,###')"/>
            </td>
          </tr>
          <tr class="rowColor2">
            <td># pages in verified documents : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td class="leftOfMergedCell" align="left">
                <xsl:value-of select="format-number(TotalPagesInVerifiedDocs, '###,###,###')"/>
              </td>
              <td class="rightOfMergedCell" align="left">
                (<xsl:value-of select="format-number(round(TotalPagesInVerifiedDocs * 100 div sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalPagesInVerifiedDocs)), '###,###,###')"/>%)
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="format-number(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalPagesInVerifiedDocs), '###,###,###')"/>
            </td>
          </tr>
          <tr class="rowColor1">
            <td># documents redacted : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td class="leftOfMergedCell" align="left">
                <xsl:value-of select="format-number(TotalDocsRedacted, '###,###,###')"/>
              </td>
              <td class="rightOfMergedCell" align="left">
                (<xsl:value-of select="format-number(round(TotalDocsRedacted * 100 div sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalDocsRedacted)), '###,###,###')"/>%)
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="format-number(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalDocsRedacted), '###,###,###')"/>
            </td>
          </tr>
          <tr class="rowColor2">
            <td># pages in redacted documents : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td class="leftOfMergedCell" align="left">
                <xsl:value-of select="format-number(TotalPagesInRedactedDocs, '###,###,###')"/>
              </td>
              <td class="rightOfMergedCell" align="left">
                (<xsl:value-of select="format-number(round(TotalPagesInRedactedDocs * 100 div sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalPagesInRedactedDocs)), '###,###,###')"/>%)
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="format-number(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/TotalPagesInRedactedDocs), '###,###,###')"/>
            </td>
          </tr>
          <tr class="rowColor1">
            <td># redactions made (including manual) : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td align="left" colspan="2">
                <xsl:value-of select="format-number(RedactionCount/Total, '###,###,###')"/>
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="format-number(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/RedactionCount/Total), '###,###,###')"/>
            </td>
          </tr>
          <tr class="rowColor2">
            <td># manual redactions made : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td align="left" colspan="2">
                <xsl:value-of select="format-number(RedactionCount/Manual, '###,###,###')"/>
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="format-number(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/RedactionCount/Manual), '###,###,###')"/>
            </td>
          </tr>
          <tr class="rowColor1">
            <td>Screen verification time : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td align="left" colspan="2">
                <xsl:variable name="numDays" select="floor(VerificationTimeInSeconds/Screen div 86400)"/>
                <xsl:variable name="numHours" select="floor((VerificationTimeInSeconds/Screen - $numDays * 86400) div 3600)"/>
                <xsl:variable name="numMinutes" select="floor((VerificationTimeInSeconds/Screen - $numDays * 86400 - $numHours * 3600) div 60)"/>
                <xsl:variable name="numSeconds" select="floor(VerificationTimeInSeconds/Screen - $numDays * 86400 - $numHours * 3600 - $numMinutes * 60)"/>
                <xsl:if test="$numDays != 0">
                  <xsl:value-of select="$numDays"/>d
                </xsl:if>
                <xsl:if test="$numDays+$numHours != 0">
                  <xsl:value-of select="$numHours"/>h
                </xsl:if>
                <xsl:if test="$numDays+$numHours+$numMinutes != 0">
                  <xsl:value-of select="$numMinutes"/>m
                </xsl:if>
                <xsl:if test="$numDays = 0">
                  <xsl:value-of select="$numSeconds"/>s
                </xsl:if>
              </td>
            </xsl:for-each>
            <td>
              <xsl:variable name="totalScreenDays" select="floor(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/VerificationTimeInSeconds/Screen) div 86400)"/>
              <xsl:variable name="totalScreenHours" select="floor((sum(/IDShieldVerificationReport/VerifierInfo/Verifier/VerificationTimeInSeconds/Screen) - $totalScreenDays * 86400) div 3600)"/>
              <xsl:variable name="totalScreenMinutes" select="floor((sum(/IDShieldVerificationReport/VerifierInfo/Verifier/VerificationTimeInSeconds/Screen) - $totalScreenDays * 86400 - $totalScreenHours * 3600) div 60)"/>
              <xsl:variable name="totalScreenSeconds" select="floor(sum(/IDShieldVerificationReport/VerifierInfo/Verifier/VerificationTimeInSeconds/Screen) - $totalScreenDays * 86400 - $totalScreenHours * 3600 - $totalScreenMinutes * 60)"/>
              <xsl:if test="$totalScreenDays != 0">
                <xsl:value-of select="$totalScreenDays"/>d
              </xsl:if>
              <xsl:if test="$totalScreenDays+$totalScreenHours != 0">
                <xsl:value-of select="$totalScreenHours"/>h
              </xsl:if>
              <xsl:if test="$totalScreenDays+$totalScreenHours+$totalScreenMinutes != 0">
                <xsl:value-of select="$totalScreenMinutes"/>m
              </xsl:if>
              <xsl:if test="$totalScreenDays = 0">
                <xsl:value-of select="$totalScreenSeconds"/>s
              </xsl:if>
            </td>
          </tr>
          <tr class="rowColor2">
            <td>Screen verification rate : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td align="left" colspan="2">
                <xsl:variable name="pagesPerHour" select="round((TotalPagesInVerifiedDocs * 3600) div VerificationTimeInSeconds/Screen)"/>
                <xsl:value-of select="$pagesPerHour"/> pages/hr
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="round((sum(IDShieldVerificationReport/VerifierInfo/Verifier/TotalPagesInVerifiedDocs) * 3600) div sum(IDShieldVerificationReport/VerifierInfo/Verifier/VerificationTimeInSeconds/Screen))"/> pages/hr
            </td>
          </tr>
          <tr class="rowColor1">
            <td>Project verification time : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td align="left" colspan="2">
                <xsl:variable name="numDays" select="floor(VerificationTimeInSeconds/Project div 86400)"/>
                <xsl:variable name="numHours" select="floor((VerificationTimeInSeconds/Project - $numDays * 86400) div 3600)"/>
                <xsl:variable name="numMinutes" select="floor((VerificationTimeInSeconds/Project - $numDays * 86400 - $numHours * 3600) div 60)"/>
                <xsl:variable name="numSeconds" select="floor(VerificationTimeInSeconds/Project - $numDays * 86400 - $numHours * 3600 - $numMinutes * 60)"/>
                <xsl:if test="$numDays != 0">
                  <xsl:value-of select="$numDays"/>d
                </xsl:if>
                <xsl:if test="$numDays+$numHours != 0">
                  <xsl:value-of select="$numHours"/>h
                </xsl:if>
                <xsl:if test="$numDays+$numHours+$numMinutes != 0">
                  <xsl:value-of select="$numMinutes"/>m
                </xsl:if>
                <xsl:if test="$numDays = 0">
                  <xsl:value-of select="$numSeconds"/>s
                </xsl:if>
              </td>
            </xsl:for-each>
            <td>
              <xsl:variable name="totalProjectDays" select="floor(IDShieldVerificationReport/ProjectInfo/TotalProjectTime div 86400)"/>
              <xsl:variable name="totalProjectHours" select="floor((IDShieldVerificationReport/ProjectInfo/TotalProjectTime - $totalProjectDays * 86400) div 3600)"/>
              <xsl:variable name="totalProjectMinutes" select="floor((IDShieldVerificationReport/ProjectInfo/TotalProjectTime - $totalProjectDays * 86400 - $totalProjectHours * 3600) div 60)"/>
              <xsl:variable name="totalProjectSeconds" select="floor(IDShieldVerificationReport/ProjectInfo/TotalProjectTime - $totalProjectDays * 86400 - $totalProjectHours * 3600 - $totalProjectMinutes * 60)"/>
              <xsl:if test="$totalProjectDays != 0">
                <xsl:value-of select="$totalProjectDays"/>d
              </xsl:if>
              <xsl:if test="$totalProjectDays+$totalProjectHours != 0">
                <xsl:value-of select="$totalProjectHours"/>h
              </xsl:if>
              <xsl:if test="$totalProjectDays+$totalProjectHours+$totalProjectMinutes != 0">
                <xsl:value-of select="$totalProjectMinutes"/>m
              </xsl:if>
              <xsl:if test="$totalProjectDays = 0">
                <xsl:value-of select="$totalProjectSeconds"/>s
              </xsl:if>
			  *
            </td>
          </tr>
          <tr class="rowColor2">
            <td>Project verification rate : </td>
            <xsl:for-each select="IDShieldVerificationReport/VerifierInfo/Verifier">
              <td align="left" colspan="2">
                <xsl:variable name="pagesPerHour" select="round((TotalPagesInVerifiedDocs * 3600) div VerificationTimeInSeconds/Project)"/>
                <xsl:value-of select="$pagesPerHour"/> pages/hr
              </td>
            </xsl:for-each>
            <td>
              <xsl:value-of select="round((IDShieldVerificationReport/ProjectInfo/TotalPagesInVerifiedDocs * 3600) div sum(IDShieldVerificationReport/ProjectInfo/TotalProjectTime))"/> pages/hr
			  *
            </td>
          </tr>
        </table>
		*These totals are created by using the earliest start time and the latest end time for all users.
      </xsl:if>
    </body>
  </html>
</xsl:template>
</xsl:stylesheet>