//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AFConditions.rc
//
#define IDS_PROJNAME                    100
#define IDR_DOCTYPECONDITION            102
#define IDS_TITLEDocTypeConditionPP     103
#define IDS_HELPFILEDocTypeConditionPP  104
#define IDS_DOCSTRINGDocTypeConditionPP 105
#define IDR_DOCTYPECONDITIONPP          106
#define IDD_DOCTYPECONDITIONPP          107
#define IDR_RSDFILECONDITION            108
#define IDS_TITLERSDFileConditionPP     109
#define IDS_HELPFILERSDFileConditionPP  110
#define IDS_DOCSTRINGRSDFileConditionPP 111
#define IDR_RSDFILECONDITIONPP          112
#define IDD_RSDFILECONDITIONPP          113
#define IDR_FINDINGRULECONDITION        114
#define IDD_FINDINGRULECONDITIONPP      115
#define IDS_TITLEFINDINGRULECONDITIONPP 116
#define IDS_HELPFILEFINDINGRULECONDITIONPP 117
#define IDS_DOCSTRINGFINDINGRULECONDITIONPP 118
#define IDR_FINDINGRULECONDITIONPP      119
#define IDR_CHARACTERCONFIDENCECONDITION 120
#define IDD_CHARACTERCONFIDENCECONDITIONPP 121
#define IDS_TITLECHARACTERCONFIDENCECONDITIONPP 122
#define IDS_HELPFILECHARACTERCONFIDENCECONDITIONPP 123
#define IDS_DOCSTRINGCHARACTERCONFIDENCECONDITIONPP 124
#define IDR_CHARACTERCONFIDENCECONDITIONPP 125
#define IDC_LIST_TYPES                  201
#define IDC_CMB_MATCH                   202
#define IDC_BTN_ADD_TYPES               203
#define IDC_BTN_REMOVE_TYPES            204
#define IDC_EDIT_RSD_FILE               204
#define IDC_BTN_CLEAR_TYPES             205
#define IDC_BTN_BROWSE                  205
#define IDC_CMB_MIN_PROBABILITY         206
#define IDI_ICON_SELECT_DOC_TAG         207
#define IDC_BTN_SELECT_DOC_TAG          208
#define IDC_CMB_CATEGORY                209
#define IDC_COMBO_OBJ                   210
#define IDC_BTN_CONFIGURE               211
#define IDC_STATIC_CONFIGURE            212
#define IDC_COMBO_FIRST_CONDITION       213
#define IDC_EDIT_FIRST_SCORE            214
#define IDC_COMBO_AND_OR                215
#define IDC_EDIT_SECOND_SCORE           216
#define IDC_COMBO_SECOND_CONDITION      217
#define IDC_BUTTON_COMMANDS_DATA_SCORER 218
#define IDC_STATIC_DATA_SCORER          219
#define IDC_CHECK_SECOND_CONDITION      220
#define IDC_STATIC_IS                   221
#define IDC_COMBO_MET					222
#define IDC_COMBO_AGGREGATE_FUNCTION	223
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         210
#define _APS_NEXT_SYMED_VALUE           126
#endif
#endif
