//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace Extract.FileActionManager.Database.SqliteModels.Version8
{
	/// <summary>
	/// Database       : ESFAMService
	/// Data Source    : ESFAMService
	/// Server Version : 3.24.0
	/// </summary>
	public partial class FAMServiceDB : LinqToDB.Data.DataConnection
	{
		public ITable<FPSFile> FPSFiles { get { return this.GetTable<FPSFile>(); } }
		public ITable<Setting> Settings { get { return this.GetTable<Setting>(); } }

		public FAMServiceDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FAMServiceDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FAMServiceDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FAMServiceDB(LinqToDBConnectionOptions<FAMServiceDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("FPSFile")]
	public partial class FPSFile
	{
		[PrimaryKey, Identity   ] public long   ID                     { get; set; } // integer
		[Column,        Nullable] public string FileName               { get; set; } // nvarchar(512)
		[Column,     NotNull    ] public int    NumberOfInstances      { get; set; } // int
		[Column,     NotNull    ] public int    NumberOfFilesToProcess { get; set; } // int
	}

	[Table("Settings")]
	public partial class Setting
	{
		[PrimaryKey, NotNull    ] public string Name  { get; set; } // nvarchar(100)
		[Column,        Nullable] public string Value { get; set; } // nvarchar(512)
	}

	public static partial class TableExtensions
	{
		public static FPSFile Find(this ITable<FPSFile> table, long ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Setting Find(this ITable<Setting> table, string Name)
		{
			return table.FirstOrDefault(t =>
				t.Name == Name);
		}
	}
}

#pragma warning restore 1591
