//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UCLIDFileProcessing.rc
//
#define IDS_PROJNAME                    100
#define IDR_FILEPROCESSINGMANAGER       102
#define IDR_FILEPROCESSINGDB            104
#define IDR_FILESUPPLIERDATA            105
#define IDR_TOOLBAR_PROCESS_FILE        106
#define IDD_DLG_ACTION_PROP             107
#define IDD_DLG_QUEUELOG_PROP           108
#define IDR_ACTIONSTATISTICS            109
#define IDR_FILESUPPLYINGMGMTROLE       110
#define IDR_FILERECORD                  111
#define IDR_FILEPROCESSINGMGMTROLE      112
#define IDR_FAMTagManager               113
#define IDR_FAMDBUTILS                  114
#define IDD_DLG_PROCESS_FILE            201
#define IDC_LIST_FILEPROCESSORS         202
#define IDC_BTN_ADD                     203
#define IDC_BTN_START                   204
#define IDC_BTN_REMOVE                  205
#define IDC_BTN_MODIFY                  206
#define IDC_BTN_LOAD_LIST               207
#define IDD_DLG_SCOPE_PROP              208
#define IDC_BTN_UP                      209
#define IDC_BTN_CLEAR                   210
#define IDD_DLG_TASK_PROP               211
#define IDC_BTN_DOWN                    212
#define IDC_BTN_FAMCONDITION            213
#define IDI_ICON_DOWN                   214
#define IDC_RADIO_INDIVIDUAL_FILES      215
#define IDI_ICON_UP                     216
#define IDC_RADIO_FOLDER                217
#define IDC_LIST_FILES                  218
#define IDD_DLG_STATUS_PROP             219
#define IDB_BMP_PASS                    220
#define IDB_BMP_FAIL                    221
#define IDC_LIST_FP                     222
#define IDC_EDIT_FOLDER                 223
#define IDB_BMP_PROGRESS                224
#define IDC_BTN_BROWSE                  225
#define IDD_DLG_TASK_INFO               226
#define IDC_CMB_FILE_EXTENSION          227
#define IDI_ICON_PROCESS                228
#define IDC_CHK_RESURSIVE               229
#define IDC_CHK_CONTINUE_PROCESS        230
#define IDI_ICON_FAIL                   231
#define IDC_CHK_SKIP                    232
#define IDI_ICON_PASS                   233
#define IDI_ICON_PROCESSING             234
#define IDC_CMB_FOLDER                  235
#define IDD_DLG_REPORT_PROP             236
#define IDC_PICTURE                     237
#define IDI_ICON_SKIPPED                238
#define IDI_ICON_PASS_LATER             239
#define IDC_GRID                        240
#define IDR_MENU_PROCESS_FILES          241
#define IDR_MENU_SELECT_DOC_TAG         242
#define IDI_ICON_SELECT_DOC_TAG         243
#define IDD_DLG_OPTIONS                 244
#define IDC_LIST_DETAIL                 245
#define IDR_MNU_CONTEXT                 246
#define IDC_CMB_SELECT_REPORT           247
#define IDC_REPORT_GRID_PROCESSED       248
#define IDC_REPORT_GRID_FAILED          249
#define IDC_LISTCTL_PRV_TASKS           250
#define IDC_REPORT_GRID_PENDING         251
#define IDC_TEXT_FINISHED_BYTES_NUM     252
#define IDC_REPORT_GRID_SKIPPED         253
#define IDC_TEXT_FINISHED_BYTES_PCT     254
#define IDC_TEXT_CURR_FILENAME          255
#define IDC_REPORT_GRID_ALL             256
#define IDC_TEXT_CURR_TASK_NUM          257
#define IDC_TEXT_TOTAL_NUM_TASKS        258
#define IDC_TEXT_TASK_NAME              259
#define IDC_BTN_SAVE_LIST               260
#define IDC_EDIT_ATTRIBUTE_SPLITTER     261
#define IDC_EDIT_CONDITION              262
#define IDC_TEXT_PROCESSING_TIME        263
#define IDC_EDIT_PATTERN                264
#define IDC_TEXT_RUN_TIME               265
#define IDC_CHK_FILTER_REGEXP           266
#define IDC_GROUP_SCOPE                 267
#define IDC_TEXT_TIME_REMAINING         268
#define IDC_CHK_CASE_SENSITIVE          269
#define IDC_TEXT_TIME_PER_DOCUMENT      270
#define IDC_CMB_FILTER_TYPE             271
#define IDC_FILTER_TYPE_TEXT            272
#define IDC_CURRENT_FILES_LIST          273
#define IDC_EDIT_SKIP_FILE_NAME         274
#define IDC_BUTTON_SELECT_DOC_TAG       275
#define IDC_BUTTON_SELECT_FOLDER_DOC_TAG 276
#define IDC_EDIT_MAX_NUM_RECORDS        277
#define IDC_CHK_RESTRICT_DISPLAYED_RECORDS 278
#define IDC_EDIT_NUM_THREADS            279
#define IDC_STATIC_OVERALL              280
#define IDC_CHK_ONLY_NEW_FILES          281
#define IDC_STATIC_THREAD_GROUP         282
#define IDC_RADIO_MAX_THREADS           283
#define IDC_RADIO_THREADS               284
#define IDC_EDIT_THREADS                285
#define IDC_STATIC_THREADS              286
#define IDC_TEXT_COMPLETION_TIME        287
#define IDC_SPIN_THREADS                288
#define IDC_STATIC_CONDITION            289
#define IDC_EDIT_VERSION                290
#define IDC_STATIC_SUPPLIER             291
#define IDD_DLG_ABOUT                   292
#define IDC_BTN_CONFIGURE               293
#define IDC_BTN_SEL_ACTION              294
#define IDC_CHK_QUEUE                   295
#define IDC_ACTION                      296
#define IDC_CHK_PROC                    297
#define IDC_CHK_DISPLAY                 298
#define IDD_DLG_SELECT_ACTION           299
#define IDC_CMB_ACTION                  300
#define IDC_STATICINFO                  301
#define IDC_BTN_EXPORT                  302
#define IDC_LIST_GLOBAL_STATS           303
#define IDC_FAILED_FILES_LIST           304
#define IDC_COMPLETE_FILES_LIST         305
#define IDC_STATIC_CURR_PROC            306
#define IDC_STATIC_COMP_PROC            307
#define IDC_STATIC_FAIL_PROC            308
#define IDC_LIST_QUEUE_LOG              309
#define IDC_LIST_LOCAL_STATS            310
#define IDC_LIST_FAILED_QUEING          311
#define IDC_CHECK_KEEP_PROCESSING_AS_ADDED 312
#define IDC_LIST_ATTEMPTING_TO_QUEUE    313
#define IDC_STATIC_TASK_LBL             314
#define IDC_STATIC_ATTEMPTING_TO_QUEUE  315
#define IDC_STATIC_QUEUE_LOG            316
#define IDC_STATIC_FAILED_QUEING        317
#define IDC_STATUSBAR                   318
#define IDC_INTERPRET_CAUTIOUSLY_HELP   319
#define IDI_ICON_CONNECTION_ESTABLISHED 323
#define IDI_ICON_CONNECTION_NOT_ESTABLISHED 324
#define IDI_ICON_CONNECTION_BUSY        325
#define IDI_ICON_WAITING_FOR_LOCK       326
#define IDR_ACCELERATORS                327
#define IDC_STATIC_INTERPRET_CAUTIOUSLY 328
#define IDI_ICON_INFO                   329
#define IDC_EDIT_FKB_VERSION            330
#define IDC_STATIC_FKB_VERSION          331
#define IDC_BTN_SELECT_ERROR_TASK       332
#define IDC_EDIT_ERROR_LOG              333
#define IDC_EDIT_EXECUTE_TASK           334
#define IDC_CHECK_EXECUTE_TASK          335
#define IDC_STATIC_ERROR_GROUP          336
#define IDC_STATIC_CONTINUOUS_GROUP     337
#define IDC_RADIO_KEEP_PROCESSING_FILES 338
#define IDC_RADIO_STOP_PROCESSING_FILES 339
#define IDC_CHECK_LOG_ERROR_DETAILS     340
#define IDC_BTN_SELECT_DOC_TAG          341
#define IDC_BTN_BROWSE_LOG              342
#define IDC_BUTTON_PROGRESS_DETAILS     344
#define IDC_BUTTON_EXCEPTION_DETAILS    345
#define IDC_BUTTON_QUEUE_EXCEPTION_DETAILS 346
#define IDC_STATIC_STATS_THIS_RUN       347
#define IDC_STATIC_FPSCOPE_GROUP        348
#define IDC_RADIO_PROCESS_ALL_FILES_PRIORITY 349
#define IDC_RADIO_PROCESS_SKIPPED_FILES 350
#define IDC_COMBO_SKIPPED_SCOPE         351
#define IDC_STATIC_SKIPPED              352
#define IDR_MENU_FAM_MRU				353
#define IDR_MENU_FAM_GRID_CONTEXT		354
#define ID_GRID_CONTEXT_COPY_FILENAME	355
#define ID_GRID_CONTEXT_OPEN_FILE		356
#define ID_GRID_CONTEXT_OPEN_FILE_LOCATION	357
#define IDC_BUTTON_DB_NAME_BROWSE       1000
#define IDC_EDIT_DB_SERVER              1001
#define IDC_EDIT_DB_NAME                1002
#define IDC_EDIT_CONNECT_STATUS         1003
#define IDD_DATABASEPAGE                1004
#define IDC_BUTTON_REFRESH              1005
#define IDC_BUTTON_SQL_SERVER_BROWSE    1006
#define IDC_BUTTON_LAST_USED_DB         1007
#define IDR_FILEPROCESSINGTASKEXECUTOR  2000
#define IDC_CHECK_LIMIT_PROCESSING      2001
#define IDC_BUTTON_SET_SCHEDULE         2002
#define IDC_STATIC_PROCESSING_SCHEDULE  2003
#define IDC_LIST_SCHEDULE               2004
#define IDD_DIALOG_SET_SCHEDULE         2005
#define IDC_BUTTON_SELECT_ALL           2007
#define IDC_BUTTON_SELECT_NONE          2008
#define IDC_BTN_ACTION_TAG              2009
#define IDC_CUSTOM1                     2010
#define IDC_CHECK1                      2011
#define IDC_BTN_RUN                     32768
#define IDC_BTN_STOP                    32769
#define IDC_BTN_AUTO_SCROLL             32770
#define IDC_BTN_CHECK_FOR_NEW_COMPONENTS 32771
#define ID_FILE_SAVEAS                  32774
#define ID_TOOLS_CHECKFORNEWCOMPONENTS  32776
#define ID_FILE_EXIT                    32778
#define ID_PROCESS_STARTPROCESSING      32780
#define ID_PROCESS_STOPPROCESSING       32781
#define ID_POPUP_SOURCEDOCNAME          32784
#define ID_POPUP_SOURCEDOCNAMEFILENAME  32785
#define ID_POPUP_SOURCEDOCNAMEPATH      32786
#define ID_POPUP_SOURCEDOCNAMEEXTENSION 32787
#define ID_TOOLS_OPTIONS                32788
#define ID_TOOLS_AUTOSCROLL             32789
#define IDC_BTN_PAUSE                   32790
#define ID_PROCESS_PAUSEPROCESSING      32791
#define ID_HELP_FILEPROCESSINGMANAGERHELP 32792
#define ID_CONTEXT_FILE                 32793
#define ID_HELP_ABOUTFILEPROCESSINGMANAGER 32794
#define ID_CONTEXT_COPY                 32795
#define ID_CONTEXT_PASTE                32796
#define ID_CONTEXT_DELETE               32797
#define ID_CONTEXT_CANCE                32798
#define ID_CONTEXT_CUT                  32799
#define ID_CONTEXT_CANCEL               32800
#define ID_TOOLS_DATABASEADMINISTRATIONUTILITY 32802
#define ID_BTN_FAM_OPEN                32803
#define ID_BTN_FAM_SAVE                 32804
#define ID_FAM_MRU_FILE1				32805
#define ID_FAM_MRU_FILE2				32806
#define ID_FAM_MRU_FILE3				32807
#define ID_FAM_MRU_FILE4				32808
#define ID_FAM_MRU_FILE5				32809
#define ID_FAM_MRU_FILE6				32810
#define ID_FAM_MRU_FILE7				32811
#define ID_FAM_MRU_FILE8				32812
#define ID_MNU_FAM_MRU					32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2006
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         2012
#define _APS_NEXT_SYMED_VALUE           2001
#endif
#endif
