//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extract.Redaction.Verification.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SlideshowInterval {
            get {
                return ((int)(this["SlideshowInterval"]));
            }
            set {
                this["SlideshowInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStartSlideshow {
            get {
                return ((bool)(this["AutoStartSlideshow"]));
            }
            set {
                this["AutoStartSlideshow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LMenu")]
        public global::System.Windows.Forms.Keys SlideshowRunKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["SlideshowRunKey"]));
            }
            set {
                this["SlideshowRunKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::Extract.Redaction.AutoTool AutoTool {
            get {
                return ((global::Extract.Redaction.AutoTool)(this["AutoTool"]));
            }
            set {
                this["AutoTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoZoom {
            get {
                return ((bool)(this["AutoZoom"]));
            }
            set {
                this["AutoZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AutoZoomScale {
            get {
                return ((int)(this["AutoZoomScale"]));
            }
            set {
                this["AutoZoomScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DoNotCreate")]
        public global::Extract.Redaction.Verification.OnDemandCreateVOAFileMode OnDemandCreateVOAFileMode {
            get {
                return ((global::Extract.Redaction.Verification.OnDemandCreateVOAFileMode)(this["OnDemandCreateVOAFileMode"]));
            }
            set {
                this["OnDemandCreateVOAFileMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoOcr {
            get {
                return ((bool)(this["AutoOcr"]));
            }
            set {
                this["AutoOcr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Balanced")]
        public global::Extract.Imaging.OcrTradeoff OcrTradeoff {
            get {
                return ((global::Extract.Imaging.OcrTradeoff)(this["OcrTradeoff"]));
            }
            set {
                this["OcrTradeoff"] = value;
            }
        }
    }
}
