/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// a line or partial line of text with the corresponding bounds and spatial position (including skew)
    /// </summary>
    [DataContract]
    public partial class SpatialLine :  IEquatable<SpatialLine>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpatialLine" /> class.
        /// </summary>
        /// <param name="SpatialLineZone">The zone - includes skew.</param>
        /// <param name="SpatialLineBounds">The bounds - the rectangular boundary that completely encloses the attribute.</param>
        public SpatialLine(SpatialLineZone SpatialLineZone = default(SpatialLineZone), SpatialLineBounds SpatialLineBounds = default(SpatialLineBounds))
        {
            this.SpatialLineZone = SpatialLineZone;
            this.SpatialLineBounds = SpatialLineBounds;
        }
        
        /// <summary>
        /// The zone - includes skew
        /// </summary>
        /// <value>The zone - includes skew</value>
        [DataMember(Name="spatialLineZone", EmitDefaultValue=false)]
        public SpatialLineZone SpatialLineZone { get; set; }
        /// <summary>
        /// The bounds - the rectangular boundary that completely encloses the attribute
        /// </summary>
        /// <value>The bounds - the rectangular boundary that completely encloses the attribute</value>
        [DataMember(Name="spatialLineBounds", EmitDefaultValue=false)]
        public SpatialLineBounds SpatialLineBounds { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpatialLine {\n");
            sb.Append("  SpatialLineZone: ").Append(SpatialLineZone).Append("\n");
            sb.Append("  SpatialLineBounds: ").Append(SpatialLineBounds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SpatialLine);
        }

        /// <summary>
        /// Returns true if SpatialLine instances are equal
        /// </summary>
        /// <param name="other">Instance of SpatialLine to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpatialLine other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SpatialLineZone == other.SpatialLineZone ||
                    this.SpatialLineZone != null &&
                    this.SpatialLineZone.Equals(other.SpatialLineZone)
                ) && 
                (
                    this.SpatialLineBounds == other.SpatialLineBounds ||
                    this.SpatialLineBounds != null &&
                    this.SpatialLineBounds.Equals(other.SpatialLineBounds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SpatialLineZone != null)
                    hash = hash * 59 + this.SpatialLineZone.GetHashCode();
                if (this.SpatialLineBounds != null)
                    hash = hash * 59 + this.SpatialLineBounds.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
