/* 
 * Document API
 *
 * Extract Document API documentation
 *
 * OpenAPI spec version: v1
 * Contact: developers@extractsystems.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Workflow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WorkflowTests
    {
        // TODO uncomment below to declare an instance variable for Workflow
        //private Workflow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Workflow
            //instance = new Workflow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Workflow
        /// </summary>
        [Test]
        public void WorkflowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Workflow
            //Assert.IsInstanceOfType<Workflow> (instance, "variable 'instance' is a Workflow");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EntryAction'
        /// </summary>
        [Test]
        public void EntryActionTest()
        {
            // TODO unit test for the property 'EntryAction'
        }
        /// <summary>
        /// Test the property 'ExitAction'
        /// </summary>
        [Test]
        public void ExitActionTest()
        {
            // TODO unit test for the property 'ExitAction'
        }
        /// <summary>
        /// Test the property 'RunAfterResultsAction'
        /// </summary>
        [Test]
        public void RunAfterResultsActionTest()
        {
            // TODO unit test for the property 'RunAfterResultsAction'
        }
        /// <summary>
        /// Test the property 'DocumentFolder'
        /// </summary>
        [Test]
        public void DocumentFolderTest()
        {
            // TODO unit test for the property 'DocumentFolder'
        }
        /// <summary>
        /// Test the property 'AttributeSetName'
        /// </summary>
        [Test]
        public void AttributeSetNameTest()
        {
            // TODO unit test for the property 'AttributeSetName'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
