// InputFinders.idl : IDL source for InputFinders.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (InputFinders.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(D76C8853-4347-11D6-826C-0050DAD4FF55),
	version(1.0),
	helpstring("UCLID InputFinders 1.0 Type Library")
]
library UCLID_INPUTFINDERSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	importlib("..\..\..\..\..\..\..\ReusableComponents\COMComponents\UCLIDCOMUtils\Core\Code\UCLIDCOMUtils.tlb");
	importlib("..\..\..\..\..\..\..\ReusableComponents\COMComponents\UCLIDComponentsLM\COMLM\Code\COMLM.tlb");
	importlib("..\..\..\..\..\..\..\ReusableComponents\COMComponents\UCLIDTestingFramework\Interfaces\Code\UCLIDTestingFramework.tlb");

	// Interfaces
	[
		object,
		uuid(D76C8860-4347-11D6-826C-0050DAD4FF55),
		dual,
		helpstring("IInputFinder Interface"),
		pointer_default(unique)
	]
	interface IInputFinder : IDispatch
	{
		[id(1), helpstring("method ParseString")] HRESULT ParseString([in] BSTR strInput, [out,retval] IIUnknownVector** ippTokenPositions);
	};

	[
		object,
		uuid(5867EAA6-41AA-480C-9793-410A65960434),
		dual,
		helpstring("IRegExprFinder Interface"),
		pointer_default(unique)
	]
	interface IRegExprFinder : IDispatch
	{
		[propget, id(1), helpstring("property Pattern")] HRESULT Pattern([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property Pattern")] HRESULT Pattern([in] BSTR newVal);
		[propget, id(2), helpstring("property IgnoreCase")] HRESULT IgnoreCase([out, retval] VARIANT_BOOL *pVal);
		[propput, id(2), helpstring("property IgnoreCase")] HRESULT IgnoreCase([in] VARIANT_BOOL newVal);
	};


	// Coclasses
	[
		uuid(D76C8863-4347-11D6-826C-0050DAD4FF55),
		helpstring("WordInputFinder Class")
	]
	coclass WordInputFinder
	{
		[default] interface IInputFinder;
		interface ICategorizedComponent;
		interface ILicensedComponent;
		interface ITestableComponent;
	};
	[
		uuid(F1EBCB34-4585-11D6-826D-0050DAD4FF55),
		helpstring("MCRTextInputFinder Class")
	]
	coclass MCRTextInputFinder
	{
		[default] interface IInputFinder;
		interface ICategorizedComponent;
		interface ILicensedComponent;
		interface ITestableComponent;
	};
	[
		uuid(445C234E-81D1-48EB-A98C-08A3A8066D6E),
		helpstring("RegExprFinder Class")
	]
	coclass RegExprFinder
	{
		[default] interface IRegExprFinder;
		interface IInputFinder;
		interface ILicensedComponent;
	};
	[
		uuid(ADAC8849-CBCF-46FA-B886-8190EEDDE4BF),
		helpstring("NothingInputFinder Class")
	]
	coclass NothingInputFinder
	{
		[default] interface IInputFinder;
		interface ICategorizedComponent;
		interface ILicensedComponent;
	};
};
