UCLIDAFCoreTest.AutomatedRuleSetTester.1;;AFCore.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFPreProcessors\AutomatedTest\LocateImageRegion\IDShieldTester.dat
UCLIDAFUtilsTest.MERSTester.1;;..\..\..\AFUtils\AFUtilsTest\TestFiles\TestMERS.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueFinders\AutomatedTest\ImageRegionWithLines\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueFinders\AutomatedTest\BoxFinder\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueFinders\AutomatedTest\LocateImageRegion\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueFinders\AutomatedTest\SelectPageRegion\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueFinders\AutomatedTest\MicrFinder\MicrFinder.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueModifiers\AutomatedTest\LocateImageRegion\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueModifiers\AutomatedTest\SSNFinder\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFValueModifiers\AutomatedTest\SplitRegionIntoContentAreas\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFSelectors\AutomatedTest\SpatialProximityAS\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFOutputHandlers\AutomatedTest\MergeAttributes\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\..\..\RC.Net\AttributeFinder\Rules\Core\AutomatedTest\ModifySpatialMode\TopLevelAttributes.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\..\..\RC.Net\AttributeFinder\Rules\Core\AutomatedTest\ModifySpatialMode\SubAttributes.dat
EXTRACTRedactionTester.IDShieldTester.1;;..\..\..\AFOutputHandlers\AutomatedTest\AutoShrinkRedactionZones\IDShieldTester.dat
EXTRACTRedactionTester.IDShieldTester;;..\..\..\IndustrySpecific\Redaction\RedactionTester\AutomatedTest\Test.dat
EXTRACTRedactionTester.IDShieldTester;;..\..\..\AFValueFinders\AutomatedTest\BarcodeFinder\spatial_test.dat
EXTRACTRedactionTester.IDShieldTester;;..\..\..\AFValueFinders\AutomatedTest\MICRFinderV2\spatial_test.dat

