@Echo off

if "%PROCESSOR_ARCHITECTURE%" == "x86" (
	"%~dp0\SQLEXPR_x86_ENU" /qs /ACTION=Install /FEATURES=SQL,Tools /INSTANCENAME=MSSQLSERVER /SQLSVCACCOUNT="NT AUTHORITY\Network Service" /SQLSYSADMINACCOUNTS="BUILTIN\Administrators" /AGTSVCACCOUNT="NT AUTHORITY\Network Service"
)
if "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
	"%~dp0\SQLEXPR_x64_ENU" /qs /ACTION=Install /FEATURES=SQL,Tools /INSTANCENAME=MSSQLSERVER /SQLSVCACCOUNT="NT AUTHORITY\Network Service" /SQLSYSADMINACCOUNTS="BUILTIN\Administrators" /AGTSVCACCOUNT="NT AUTHORITY\Network Service"
)
