@Echo off

if "%PROCESSOR_ARCHITECTURE%" == "x86" (
	%~dp0\SQLEXPR_x86_ENU /q /ACTION=Install /FEATURES=SQL,Tools /INSTANCENAME=MSSQLSERVER /INDICATEPROGRESS /SQLSVCACCOUNT="NT AUTHORITY\Network Service" /SQLSYSADMINACCOUNTS="BUILTIN\Administrators" /AGTSVCACCOUNT="NT AUTHORITY\Network Service"
)
if "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
	%~dp0\SQLEXPR_x64_ENU /q /ACTION=Install /FEATURES=SQL,Tools /INSTANCENAME=MSSQLSERVER /INDICATEPROGRESS /SQLSVCACCOUNT="NT AUTHORITY\Network Service" /SQLSYSADMINACCOUNTS="BUILTIN\Administrators" /AGTSVCACCOUNT="NT AUTHORITY\Network Service"
)
