IcoMapESRIVersion=IcoMapESRI Ver. 4.2.7.4
IcoMapCoreVersion=IcoMapCore Ver. 4.2.7.4
ReusableComponentsVersion=RC Ver. 8.0.0.4
PDUtilsVersion=PDUtils Ver. 3.5.0.4
PlatformSpecificUtilsVersion=PlatSpecUtils Ver. 2.7.3.4
RCDotNetVersion=RC.Net Ver. 2.0.0.4
LaserficheVersion=Integration LF Ver. 1.0.5.4
FlexIndexVersion=FlexIndex Ver. 8.0.0.4
IDShieldOfficeVersion=IDShield Office Ver. 1.0.5.4
LabDEVersion=LabDE Ver. 1.0.4.4
RulesVersion=Rules Ver. 2.0.0.4
FKBVersion=FKB Ver. 9.1+
