ReusableComponentsVersion=RC Ver. 9.1.0.5
PDUtilsVersion=PDUtils Ver. 9.1.0.5
PlatformSpecificUtilsVersion=PlatSpecUtils Ver. 9.1.0.5
RCDotNetVersion=RC.Net Ver. 9.1.0.5
LaserficheVersion=Integration LF Ver. 9.1.0.5
FlexIndexVersion=FlexIndex Ver. 9.1.0.5
IDShieldOfficeVersion=IDShield Office Ver. 9.1.0.5
DataEntryVersion=DataEntry Ver. 9.1.0.5
LabDEVersion=LabDE Ver. 9.1.0.5
RulesVersion=Rules Ver. 9.1.0.5
FlexIDSSPVersion=FlexIDS for SP Ver. 9.1.0.5
FlexIDSNetDMSVersion=FlexIDS for NetDMS Ver. 9.1.0.5
FKBVersion=FKB Ver. 12.2.0.5