
#pragma once

class UCLIDException;

// Import for using the email functionality for the alerts
#import "..\..\..\APIs\LeadTools_13\bin\LTCML13N.DLL" no_namespace \
	rename("SendMessage", "LTSendMessage") \
	rename("GetMessage", "LTGetMessage")

/*
#define EML_VIEWDLG_CLOSED	8
#define EML_VIEWDLG_FORWARD	7
#define EML_VIEWDLG_REPLYALL	6
#define EML_VIEWDLG_REPLY	5
#define EML_COMPDLG_CANCELED	4
#define EML_COMPDLG_MESSAGE_UPDATED	3
#define EML_COMPDLG_MESSAGE_SENT	2
#define EML_SUCCESS	1
#define EML_ERROR_ALLOC_MEMORY_FAILED	20001
#define EML_ERROR_SOCKET_ERROR	20002
#define EML_ERROR_RESOLVE_HOST_FAILED	20003
#define EML_ERROR_TIMEOUT	20004
#define EML_ERROR_FAILED	20005
#define EML_ERROR_CONNECTION_CLOSED	20006
#define EML_ERROR_UNEXPECTED_SERVER_RESPONSE	20007
#define EML_ERROR_AUTHENTICATION_FAILED	20008
#define EML_ERROR_NO_AUTHORS_SPECIFIED	20009
#define EML_ERROR_MUST_SPECIFY_SENDER	20010
#define EML_ERROR_NO_RECIPIENTS_SPECIFIED	20011
#define EML_ERROR_INVALID_DISPLAY_NAME	20012
#define EML_ERROR_INVALID_EMAIL_ADDRESS	20013
#define EML_ERROR_INVALID_PARAMETER	20014
#define EML_ERROR_INVALID_HEADER_FIELD_BODY	20015
#define EML_ERROR_INVALID_HEADER_FIELD_NAME	20016
#define EML_ERROR_MUST_ENCODE_BODY	20017
#define EML_ERROR_INVALID_FORMAT	20018
#define EML_ERROR_INVALID_CHARSET	20019
#define EML_ERROR_ADDING_ATTACHMENT_FAILED	20020
#define EML_ERROR_OPERATION_CANCELLED	20021
#define EML_ERROR_SOCK_INIT_FAILED	20101
#define EML_ERROR_INVALID_WND_HANDLE	20102
#define EML_ERROR_CREATE_DLG_FAILED	20103
*/

// if the result is > the following the result is an error
#define EML_ERROR 20000

void loadLTEmailErrInfo(UCLIDException& ue, short nStatus);
