//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - AJUD.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - ATDE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - BLANK.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - CLUP.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - DTRU.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - GDEE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - NCOM.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - NDEF.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - NFTL.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - NSJU.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - NSTL.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - NTSA.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - QCDE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - RECO.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - REND.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - RLIE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - STRU.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - TDEE.dat
//UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - TTDE.dat
UCLIDAFCoreTest.AutomatedRuleSetTester.1;;CA - Santa Barbara - Index Item - Issue11.dat
