//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AFValueFinders.rc
//
#define IDS_PROJNAME                    100
#define IDR_VALUEAFTERCLUE              102
#define IDR_VALUEBEFORECLUE             103
#define IDR_VALUEFROMLIST               104
#define IDR_REGEXPRRULE                 106
#define IDS_TITLERegExprRulePP          107
#define IDS_HELPFILERegExprRulePP       108
#define IDS_DOCSTRINGRegExprRulePP      109
#define IDR_REGEXPRRULEPP               110
#define IDD_REGEXPRRULEPP               111
#define IDS_TITLEValueAfterCluePP       112
#define IDS_HELPFILEValueAfterCluePP    113
#define IDS_DOCSTRINGValueAfterCluePP   114
#define IDR_VALUEAFTERCLUEPP            115
#define IDD_VALUEAFTERCLUEPP            116
#define IDS_TITLEValueBeforeCluePP      117
#define IDS_HELPFILEValueBeforeCluePP   118
#define IDS_DOCSTRINGValueBeforeCluePP  119
#define IDR_VALUEBEFORECLUEPP           120
#define IDD_VALUEBEFORECLUEPP           121
#define IDS_TITLEValueFromListPP        122
#define IDS_HELPFILEValueFromListPP     123
#define IDS_DOCSTRINGValueFromListPP    124
#define IDR_VALUEFROMLISTPP             125
#define IDD_VALUEFROMLISTPP             126
#define IDR_EXTRACTLINE                 127
#define IDS_TITLEExtractLinePP          128
#define IDS_HELPFILEExtractLinePP       129
#define IDS_DOCSTRINGExtractLinePP      130
#define IDR_EXTRACTLINEPP               131
#define IDD_EXTRACTLINEPP               132
#define IDR_LEGALDESCRIPTIONFINDER      133
#define IDR_BLOCKFINDER                 134
#define IDS_TITLEBlockFinderPP          135
#define IDS_HELPFILEBlockFinderPP       136
#define IDS_DOCSTRINGBlockFinderPP      137
#define IDR_BLOCKFINDERPP               138
#define IDD_BLOCKFINDERPP               139
#define IDR_SPMFINDER                   140
#define IDS_TITLESPMFinderPP            141
#define IDS_HELPFILESPMFinderPP         142
#define IDS_DOCSTRINGSPMFinderPP        143
#define IDR_SPMFINDERPP                 144
#define IDD_SPMFINDERPP                 145
#define IDR_RETURNADDRFINDER            146
#define IDR_LOCATEIMAGEREGION           147
#define IDS_TITLELocateImageRegionPP    148
#define IDS_HELPFILELocateImageRegionPP 149
#define IDS_DOCSTRINGLocateImageRegionPP 150
#define IDR_LOCATEIMAGEREGIONPP         151
#define IDD_LOCATEIMAGEREGIONPP         152
#define IDR_ADDRESSFINDER               153
#define IDS_TITLEReturnAddrFinderPP     154
#define IDS_HELPFILEReturnAddrFinderPP  155
#define IDS_DOCSTRINGReturnAddrFinderPP 156
#define IDR_RETURNADDRFINDERPP          157
#define IDD_RETURNADDRFINDERPP          158
#define IDR_CREATEVALUE                 159
#define IDS_TITLECreateValuePP          160
#define IDS_HELPFILECreateValuePP       161
#define IDS_DOCSTRINGCreateValuePP      162
#define IDR_CREATEVALUEPP               163
#define IDD_CREATEVALUEPP               164
#define IDR_FINDFROMRSD                 165
#define IDS_TITLEFindFromRSDPP          166
#define IDS_HELPFILEFindFromRSDPP       167
#define IDS_DOCSTRINGFindFromRSDPP      168
#define IDR_FINDFROMRSDPP               169
#define IDD_FINDFROMRSDPP               170
#define IDR_CONDITIONALVALUEFINDER      171
#define IDR_IMAGEREGIONWITHLINES        172
#define IDD_IMAGEREGIONWITHLINESPP      173
#define IDS_TITLEIMAGEREGIONWITHLINESPP 174
#define IDS_HELPFILEIMAGEREGIONWITHLINESPP 175
#define IDS_DOCSTRINGIMAGEREGIONWITHLINESPP 176
#define IDR_IMAGEREGIONWITHLINESPP      177
#define IDR_BOXFINDER                   178
#define IDD_BOXFINDERPP                 179
#define IDR_BOXFINDERPP                 180
#define IDD_LOOPFINDERPP                181
#define IDS_TITLELOOPFINDERPP           182
#define IDS_HELPFILELOOPFINDERPP        183
#define IDS_DOCSTRINGLOOPFINDERPP       184
#define IDR_LOOPFINDERPP                185
#define IDR_LOOPFINDER                  186
#define IDR_MICRFINDER                  187
#define IDR_MICRFINDERPP                188
#define IDD_MICRFINDERPP                189
#define IDS_TITLEMICRFINDERPP           190
#define IDS_HELPFILEMICRFINDERPP        191
#define IDS_DOCSTRINGMICRFINDERPP       192
#define IDR_CHECKFINDER                 193
#define IDC_EDIT_PATTERN                201
#define IDI_ICON_INFO                   202
#define IDC_LIST_VALUE_LIST             203
#define IDC_CHK_CASE_FROM_LIST          204
#define IDC_BTN_ADD_VALUE_TO_LIST       205
#define IDC_BTN_REMOVE_VALUE_FROM_LIST  206
#define IDC_BTN_MODIFY_VALUE_IN_LIST    207
#define IDC_BTN_LOAD_VALUE_LIST_FILE    208
#define IDI_ICON_NOTEPAD                209
#define IDC_CHK_REG_EXP_CASE            210
#define IDC_BTN_SAVE_VALUE_LIST_FILE    211
#define IDC_LIST_AFTER_CLUE             212
#define IDC_CHK_NAMED_MATCHES_AS_SUBATTRIBUTES 213
#define IDC_BTN_ADD_AFTER_CLUE          214
#define IDI_ICON_UP                     215
#define IDC_BTN_REMOVE_AFTER_CLUE       216
#define IDI_ICON_DOWN                   217
#define IDC_BTN_MODIFY_AFTER_CLUE       218
#define IDI_ICON_POPULATED              219
#define IDC_RADIO_NO_TYPE_AC            220
#define IDI_ICON_EMPTY                  221
#define IDC_RADIO_UPTO_XWORDS_AC        222
#define IDC_CHK_STOP_AT_NEWLINE_AC      223
#define IDC_EDIT_NUM_OF_WORDS_AC        224
#define IDC_EDIT_OTHER_PUNC_AC          225
#define IDC_CHK_SPACES_AC               226
#define IDC_EDIT_OTHER_STOP_AC          227
#define IDC_RADIO_CLUE_LINE_AC          228
#define IDC_RADIO_UPTO_XLINES_AC        229
#define IDC_EDIT_NUM_OF_LINES_AC        230
#define IDC_CHK_INCLUDE_CLUE_LINE_AC    231
#define IDC_CHK_CASE_AC                 232
#define IDC_RADIO_CLUE_TO_STRING_AC     233
#define IDC_EDIT_STRING_SPEC_AC         234
#define IDI_ICON_SELECT_DOC_TAG         235
#define IDC_RADIO_CLUE_TO_REGEXPR_AC    236
#define IDC_EDIT_REGEX_SPEC_AC          237
#define IDC_CHK_OTHER_PUNC_AC           238
#define IDC_LIST_BEFORE_CLUE            239
#define IDC_CHK_OTHER_STOP_AC           240
#define IDC_BTN_ADD_BEFORE_CLUE         241
#define IDC_BTN_REMOVE_BEFORE_CLUE      242
#define IDC_BTN_MODIFY_BEFORE_CLUE      243
#define IDC_RADIO_NO_TYPE_BC            244
#define IDC_RADIO_UPTO_XWORDS_BC        245
#define IDC_RADIO_CLUE_LINE_BC          246
#define IDC_EDIT_NUM_OF_WORDS_BC        247
#define IDC_CHK_STOP_AT_NEWLINE_BC      249
#define IDC_CHK_SPACES_BC               250
#define IDC_CHK_OTHER_PUNC_BC           251
#define IDC_EDIT_OTHER_PUNC_BC          252
#define IDC_RADIO_UPTO_XLINES_BC        253
#define IDC_EDIT_NUM_OF_LINES_BC        254
#define IDC_CHK_INCLUDE_CLUE_LINE_BC    255
#define IDC_RADIO_CLUE_TO_STRING_BC     256
#define IDC_EDIT_STRING_SPEC_BC         257
#define IDC_RADIO_CLUE_TO_REGEXPR_BC    258
#define IDC_EDIT_REGEX_SPEC_BC          259
#define IDC_CHK_CASE_BC                 260
#define IDC_CHK_AS_REGEXPR_AC           261
#define IDC_BTN_SELECT_DOC_TAG          262
#define IDC_CHK_OTHER_STOP_BC           263
#define IDC_CHK_AS_REGEXPR_BC           264
#define IDC_EDIT_OTHER_STOP_BC          265
#define IDC_RADIO_EXTRACT_LINES         266
#define IDC_CHECK_FIND_NON_RETURN_ADDRESSES 267
#define IDC_EDIT_LINE_NUMBER            268
#define IDC_RADIO_UNIQUE                269
#define IDC_RADIO_EXTRACT_LINES2        270
#define IDC_EDIT_LINE_NUMBER2           271
#define IDC_LINE_INFO                   272
#define IDC_EDIT_SEPARATOR              273
#define IDC_CHK_INPUT_AS_BLOCK          274
#define IDC_RADIO_FIND_ALL              275
#define IDC_RADIO_BLOCK_WITH_CLUE       276
#define IDC_EDIT_MIN_NUMBER             277
#define IDC_LIST_CLUES                  278
#define IDC_BTN_ADD_BF                  279
#define IDC_BTN_REMOVE_BF               280
#define IDC_BTN_MODIFY_BF               281
#define IDC_CHK_AS_REG_EXP              282
#define IDC_CHK_GET_MAX                 283
#define IDC_CHK_PART_OF_WORD            284
#define IDC_CHK_STRING_AS_REGEXPR_AC    285
#define IDC_RADIO_DEFINE_BLOCKS_SEPARATOR 286
#define IDC_CHK_STRING_AS_REGEXPR_BC    288
#define IDC_RADIO_DEFINE_BLOCKS_BEGINEND 289
#define IDC_EDIT_BLOCK_BEGIN            290
#define IDC_BLOCK_SEPARATOR_HELP_BF     291
#define IDC_CLUES_HELP_BF               292
#define IDC_PART_WORD_HELP_BF           293
#define IDC_MAX_HELP_BF                 294
#define IDC_STOP_CHAR_HELP_VA           295
#define IDC_EDIT_BLOCK_END              296
#define IDC_SEPARATOR_HELP_VA           297
#define IDC_CHK_PAIRBEGINEND            298
#define IDC_STOP_CHAR_HELP_VB           299
#define IDC_SEPARATOR_HELP_VB           300
#define IDC_EDIT_PATTERN_TEXT           301
#define IDC_RADIO_TEXT                  302
#define IDC_RADIO_FILE                  303
#define IDC_EDIT_RULE_FILE              304
#define IDC_BTN_BROWSE_SPM              305
#define IDC_BTN_OPEN_NOTEPAD            306
#define IDC_EDIT_RULE_WORKED_NAME       307
#define IDC_CHK_CASE_SPM                308
#define IDC_CHK_MULTIPLE_WS             309
#define IDC_BTN_ADVANCE                 310
#define IDC_CHK_IGNORE_NO_TAGS          311
#define IDC_TEXT_DEFINE_NAME            312
#define IDC_CHK_GREEDY                  313
#define IDC_PATTERN_TEXT                314
#define IDC_CHK_STORE_RULE_WORKED       315
#define IDC_PATTERN_FILE_INFO           316
#define IDC_BTN_BROWSE_REG_EXP          317
#define IDC_MIN_SCORE_INFO              318
#define IDC_EDIT_REG_EXP_FILE           319
#define IDC_RULEID_TAG_INFO             320
#define IDC_REG_EXP_FILE_INFO           321
#define IDC_MIN_FIRST_SCORE_INFO        322
#define IDC_CMB_INSIDE                  323
#define IDC_CMB_INCLUDE                 324
#define IDC_CMB_INTERSECTING            325
#define IDC_OPT_LIST1                   326
#define IDC_OPT_LIST2                   327
#define IDC_OPT_LIST3                   328
#define IDC_OPT_LIST4                   329
#define IDC_CMB_MATCH_PER_DOC           330
#define IDC_BTN_ADD_LR                  331
#define IDC_BTN_REMOVE_LR               332
#define IDC_BTN_MODIFY_LR               333
#define IDC_BTN_UP_LR                   334
#define IDC_BTN_DOWN_LR                 335
#define IDC_CHK_AS_REGEXPR_LR           336
#define IDC_CHK_RESTRICT                337
#define IDC_CMB_SIDE1                   338
#define IDC_CMB_CONDITION1              339
#define IDC_CHK_EXPAND_UP               340
#define IDC_EDIT_NUM1                   341
#define IDC_CMB_SIDE2                   342
#define IDC_CMB_CONDITION2              343
#define IDC_CMB_ENTITY1                 344
#define IDC_TEXT_LIST_NUM               345
#define IDC_PIC_ICON_1                  346
#define IDC_PIC_ICON_2                  347
#define IDC_PIC_ICON_3                  348
#define IDC_PIC_ICON_4                  349
#define IDC_CHK_EXPAND_DOWN             350
#define IDC_EDIT_NUM2                   351
#define IDC_CMB_SIDE3                   352
#define IDC_CMB_CONDITION3              353
#define IDC_CHK_EXPAND_LEFT             354
#define IDC_EDIT_NUM3                   355
#define IDC_CMB_SIDE4                   356
#define IDC_CMB_CONDITION4              357
#define IDC_CHK_EXPAND_RIGHT            358
#define IDC_EDIT_NUM4                   359
#define IDC_CMB_ENTITY2                 360
#define IDC_CHK_CASE_SENSITIVE_LR       361
#define IDC_BUTTON_SELECT_DATA_SCORER   362
#define IDC_EDIT_MIN_SCORE              363
#define IDC_RADIO_RETURN_FIRST_MATCH    364
#define IDC_RADIO_RETURN_BEST_MATCH     365
#define IDC_RADIO_RETURN_ALL_MATCHES    366
#define IDC_STATIC_MIN_SCORE_LABEL      367
#define IDC_STATIC_DATA_SCORER          368
#define IDC_EDIT_MIN_FIRST_SCORE        369
#define IDC_LIST_PREPROCESSORS          370
#define IDC_BTN_ADD_SPM                 371
#define IDC_BTN_REMOVE_SPM              372
#define IDC_BTN_MODIFY_SPM              373
#define IDC_PREPROCESSOR_INFO           374
#define IDC_RADIO_RETURN_FIRST_OR_BEST  375
#define IDC_STATIC_MIN_FIRST_SCORE_LABEL 376
#define IDC_EDIT_VALUE                  377
#define IDC_EDIT_TYPE                   378
#define IDC_EDIT_ATTRIBUTE_NAME         379
#define IDC_EDIT_RSD_FILE               380
#define IDC_BTN_BROWSE                  381
#define IDC_CMB_FIND_TYPE               382
#define IDC_EDIT1                       383
#define IDC_EDT_IMAGE_REGION_TEXT       384
#define IDC_CMB_EXPAND_DIR_TOP          385
#define IDC_BTN_LOAD_LIST               386
#define IDC_CMB_EXPAND_DIR_BOTTOM       387
#define IDC_CMB_EXPAND_DIR_LEFT         388
#define IDC_CMB_EXPAND_DIR_RIGHT        389
#define IDC_BTN_SAVE_LIST               390
#define IDC_CLUE_DYNAMIC_LIST_HELP      391
#define IDI_ICON_DYNAMIC_LIST           392
#define IDC_STATIC_LOC_REG_ON           393
#define IDC_STATIC_REGION_ON            394
#define IDC_EDIT_WIDTH_MIN              395
#define IDC_EDIT_WIDTH_MAX              396
#define IDC_COMBO_COLUMNS_MIN           397
#define IDC_COMBO_COLUMNS_MAX           398
#define IDC_COMBO_LINES_MIN             399
#define IDC_COMBO_LINES_MAX             400
#define IDC_RADIO_ALL_PAGES             401
#define IDC_EDIT_LINE_SPACING_MIN       402
#define IDC_EDIT_LINE_SPACING_MAX       403
#define IDC_EDIT_COLUMN_SPACING_MAX     404
#define IDC_CHK_INCLUDE_LINES           405
#define IDC_RADIO_SPECIFIED_PAGES       406
#define IDC_RADIO_FIRST_PAGES           407
#define IDC_RADIO_LAST_PAGES            408
#define IDC_EDIT_FIRST_PAGE_NUMS        409
#define IDC_EDIT_LAST_PAGE_NUMS         410
#define IDC_EDIT_SPECIFIED_PAGE_NUMS    411
#define IDC_EDIT_ATTRIBUTE_TEXT         412
#define IDC_PICT_CLUE_DIAGRAM           413
#define IDC_RADIO_RETURN_BOX_AREA       414
#define IDC_CHECK_EXCLUDE_CLUE_AREA     415
#define IDC_RADIO_RETURN_TEXT           416
#define IDC_CHECK_INCLUDE_CLUE_TEXT     417
#define IDB_BITMAP_CLUESAME             418
#define IDB_BITMAP_CLUETOPLEFT          419
#define IDB_BITMAP_CLUETOP              420
#define IDB_BITMAP_CLUETOPRIGHT         421
#define IDB_BITMAP_CLUELEFT             422
#define IDB_BITMAP_CLUERIGHT            423
#define IDB_BITMAP_CLUEBOTTOMLEFT       424
#define IDB_BITMAP_CLUEBOTTOM           425
#define IDB_BITMAP_CLUEBOTTOMRIGHT      426
#define IDC_EDIT_BOX_HEIGHT_MIN         427
#define IDC_EDIT_BOX_WIDTH_MIN          428
#define IDC_EDIT_BOX_HEIGHT_MAX         429
#define IDC_EDIT_BOX_WIDTH_MAX          430
#define IDC_CHK_AS_REGEXPR              431
#define IDC_CHK_CASE_SENSITIVE          432
#define IDC_BTN_ADD_CLUE                433
#define IDC_BTN_REMOVE_CLUE             434
#define IDC_BTN_MODIFY_CLUE             435
#define IDC_CHECK_INCLUDE_LINES         436
#define IDC_CHK_FIRST_CLUE_ONLY         437
#define IDC_CHK_FIRST_BOX_ONLY          438
#define IDC_BTN_CLUE_UP                 439
#define IDC_BTN_CLUE_DOWN               440
#define IDC_RADIO_DO                    441
#define IDC_RADIO_WHILE                 442
#define IDC_RADIO_FOR                   443
#define IDC_LOOP_TYPE                   444
#define IDC_STATIC_BEGIN_LOOP_TEXT      446
#define IDC_BUTTON_CONFIGURE_FINDING_RULE 447
#define IDC_BUTTON_CONFIGURE_PREPROCESSOR 448
#define IDC_BUTTON_CONFIGURE_CONDITION  449
#define IDC_EDIT_ITERATIONS             450
#define IDC_CHECK_LOG_EXCEPTION         451
#define IDC_COMBO_CONDITION_VALUE       452
#define IDC_STATIC_END_LOOP_TEXT        453
#define IDC_STATIC_ITERATION_TEXT       454
#define IDC_STATIC_BEGIN_LOOP_BRACE     455
#define IDC_STATIC_FINDING_RULE         456
#define IDC_STATIC_PRE_PROCESSOR        457
#define IDC_STATIC_LOOP_SETUP           458
#define IDC_EDIT_FINDING_RULE           459
#define IDC_EDIT_PREPROCESSOR           460
#define IDC_EDIT_CONDITION              461
#define IDC_CHECK_SPLIT_ROUTING			462
#define IDC_CHECK_SPLIT_ACCOUNT			463
#define IDC_CHECK_SPLIT_CHECK			464
#define IDC_CHECK_SPLIT_AMOUNT			465
#define IDC_CHECK_0_ROTATION            466
#define IDC_CHECK_90_ROTATION           467
#define IDC_CHECK_180_ROTATION          468
#define IDC_CHECK_270_ROTATION          469

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1002
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         470
#define _APS_NEXT_SYMED_VALUE           194
#endif
#endif
