//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IcoMapApp.rc
//
#define IDS_PROJNAME                    100
#define IDR_ICOMAPCTL                   102
#define IDR_ICOMAPINPUTCONTEXT          104
#define IDR_ICOMAPCOMMANDRECOGNIZER     105
#define IDR_NOTHINGINPUTVALIDATOR       106
#define IDD_DLG_INPUT_CORRECTION        133
#define IDC_BTN_ReverseMode             207
#define IDC_BTN_ToggleCurveDirection    208
#define IDD_DLG_IcoMap                  209
#define IDC_BTN_ToggleDeltaAngle        209
#define IDC_BTN_DrawingTools            210
#define IDC_BTN_SketchTools             211
#define IDB_BMP_Curve1                  211
#define IDC_TEXT_TYPE                   213
#define IDC_PICTURE_TOOLTIP             214
#define IDC_BTN_ImageRecognition        217
#define IDC_CHECK_AUTO_LINKING_SRCDOC   217
#define IDC_BTN_LegalText               218
#define IDC_CHECK_ENTER_DEFAULT_VALUE   218
#define IDC_FRAME_OUTPUT                219
#define IDC_RADIO_SAME_AS_IMAGE         220
#define IDB_BMP_Not                     221
#define IDC_RADIO_OTHER                 221
#define IDB_BMP_Check                   222
#define IDC_EDIT_LOACTION               222
#define IDD_GENERAL_SETTINGS            223
#define IDC_BTN_BROWSE                  223
#define IDD_RECOGNITION_SETTINGS        224
#define IDC_STATIC_HEADER               224
#define IDC_EDIT_Prompt                 225
#define IDD_KEYBOARD_SETTINGS           225
#define IDC_EDIT_NW                     225
#define IDC_EDIT_Input                  226
#define IDC_EDIT_N                      226
#define IDC_BTN_Options                 227
#define IDC_EDIT_NE                     227
#define IDC_BTN_SelectFeatures          228
#define IDC_EDIT_W                      228
#define IDC_BTN_Help                    229
#define IDC_EDIT_E                      229
#define IDC_EDIT_SW                     230
#define IDC_BTN_Collapse                231
#define IDC_EDIT_S                      231
#define IDC_STATIC_Status               232
#define IDC_BTN_NormalMode              232
#define IDC_EDIT_SE                     232
#define IDC_BTN_ToggleLeft              233
#define IDC_EDIT_L                      233
#define IDC_BTN_ToggleRight             234
#define IDC_EDIT_R                      234
#define IDC_BTN_DeltaAngle_GT180        235
#define IDC_STATIC_NW                   235
#define IDC_BTN_DeltaAngle_LT180        236
#define IDC_STATIC_N                    236
#define IDC_STATIC_NE                   237
#define IDC_STATIC_W                    238
#define IDC_STATIC_E                    239
#define IDC_STATIC_SW                   240
#define IDC_STATIC_S                    241
#define IDC_STATIC_SE                   242
#define IDC_STATIC_L                    243
#define IDC_STATIC_R                    244
#define IDD_DLG_CurveWizard             247
#define IDC_RADIO_Curve1                248
#define IDC_RADIO_Curve2                249
#define IDC_RADIO_Curve3                250
#define IDC_RADIO_Curve4                251
#define IDC_RADIO_Curve5                252
#define IDC_RADIO_Curve6                253
#define IDC_RADIO_Curve7                254
#define IDD_DLG_CurveWizardReset        255
#define IDC_RADIO_Curve8                255
#define IDD_DLG_CurveWizardSaveAs       256
#define IDC_CHK_Curve1                  256
#define IDC_CHK_Curve2                  257
#define IDC_CHK_Curve3                  258
#define IDC_CHK_Curve4                  259
#define IDC_CHK_Curve5                  260
#define IDC_CHK_Curve6                  261
#define IDC_CHK_Curve7                  262
#define IDD_DLG_HELP_ABOUT              262
#define IDC_CHK_Curve8                  263
#define IDR_MNU_ICOMAP                  263
#define IDC_BTN_SaveAs                  264
#define IDC_BTN_Reset                   265
#define IDI_ICON_ICOMAP                 265
#define IDC_CBN_Parameter1              267
#define IDB_BITMAP_SPLASH               267
#define IDC_CBN_Parameter2              268
#define IDD_DLG_SelectFeatures          268
#define IDC_CBN_Parameter3              269
#define IDR_TOOLBAR_ICOMAP              269
#define IDC_BTN_SelectAll               270
#define IDC_BTN_PIN                     273
#define IDR_MNU_DRAWING_TOOLS           273
#define IDC_BTN_CONFIRM_TOGGLE          274
#define IDR_MNU_SKETCH_TOOLS            274
#define IDB_BMP_LINE                    275
#define IDC_BTN_PINNED                  275
#define IDC_RADIO_FEET                  276
#define IDC_RADIO_METERS                277
#define IDB_BMP_Curve2                  277
#define IDB_BMP_Curve3                  278
#define IDC_EDIT_SOURCE_DOC             279
#define IDB_BMP_Curve8                  279
#define IDB_BMP_Curve5                  280
#define IDC_RADIO_NODE_LOCKED           280
#define IDB_BMP_Curve6                  281
#define IDC_RADIO_FLOATING              281
#define IDB_BMP_Curve7                  282
#define IDC_EDIT_NAMING_SERVICE_IORFILE 282
#define IDB_BMP_Curve4                  283
#define IDC_BUTTON_BROWSE               283
#define IDC_EDIT_REGISTRATION_KEY       284
#define IDC_RADIO_EVALUATION            284
#define IDC_EDIT_VERSION                285
#define IDC_EDIT_EVALUATION             285
#define IDC_EDIT_COUNTER_INFO           286
#define IDC_EDIT_CURVE1                 287
#define IDB_BMP_GENIE                   288
#define IDC_EDIT_CURVE2                 288
#define IDB_BMP_Reverse                 289
#define IDC_EDIT_CURVE3                 289
#define IDB_BMP_Right                   290
#define IDC_EDIT_CURVE4                 290
#define IDB_BMP_GT180                   291
#define IDC_EDIT_CURVE5                 291
#define IDC_EDIT_CURVE6                 292
#define IDB_BMP_ORIGIN                  293
#define IDC_EDIT_CURVE7                 293
#define IDC_EDIT_CURVE8                 294
#define IDC_EDIT_LINE                   295
#define IDC_EDIT_LINE_ANGLE             296
#define IDC_EDIT_CUSTOM                 297
#define IDC_EDIT_RIGHT                  298
#define IDC_EDIT_LEFT                   299
#define IDC_EDIT_LESS                   300
#define IDB_BMP_Collapse                300
#define IDC_EDIT_GREATER                301
#define IDD_LM_SETTINGS                 302
#define IDC_EDIT_CONFIRM                303
#define IDC_EDIT_FORWARD                304
#define IDC_EDIT_REVERSE                305
#define IDC_EDIT_FINISHSKETCH           306
#define IDC_EDIT_FINISHPART             307
#define IDC_EDIT_DELETESKETCH           308
#define IDC_BUTTON_RESTORE              309
#define IDC_SPIN_PRECISION              310
#define IDI_ICON_COLLAPSE               311
#define IDC_EDIT_PRECISION              312
#define IDD_SHORTCUT_SETTINGS           313
#define IDC_EDIT_EXPIRATION_DATE        314
#define IDC_EDIT_PDF_RESOLUTION         315
#define IDI_ICON_GENIE                  316
#define IDC_INPUTMANAGER1               317
#define IDC_RADIO_Bearing               318
#define IDI_ICON_OPTIONS                319
#define IDC_RADIO_Angle                 320
#define IDC_RADIO_PolarAngle            321
#define IDD_DLG_DIRECTION_SETTINGS      322
#define IDC_RADIO_Azimuth               323
#define IDB_BMP_LINE_ANGLE              324
#define IDC_CMB_UNIT_TYPE               325
#define IDC_RADIO_Deflection            326
#define IDC_RADIO_Internal              327
#define IDC_STATIC_NOTE                 328
#define IDC_CHECK_CPEN_LICENSED         329
#define IDC_CHECK_CREATE_ICOMAPATTR     330
#define IDC_RW_DIG                      331
#define IDR_MNU_DIG_CONTEXT             332
#define IDC_DSTEXT                      333
#define IDC_LIST_CHOICES                1008
#define IDC_EDIT_TEXT                   1009
#define IDC_BITMAP_GOOD                 1109
#define IDC_BITMAP_BAD                  1110
#define ID_FILE_NEWLEGALTEXTWINDOW      32768
#define ID_FILE_NEWIMAGERECOGNITIONWINDOW 32769
#define ID_TOOLS_ACTIONS_FINISHPART     32772
#define ID_TOOLS_ACTIONS_DELETESKETCH   32773
#define ID_TOOLS_DRAWINGTOOLS_LINE      32774
#define ID_TOOLS_DRAWINGTOOLS_LINEANGLE 32775
#define ID_TOOLS_DRAWINGTOOLS_CURVE1    32776
#define ID_TOOLS_DRAWINGTOOLS_CURVE2    32777
#define ID_TOOLS_DRAWINGTOOLS_CURVE3    32778
#define ID_TOOLS_DRAWINGTOOLS_CURVE4    32779
#define ID_TOOLS_DRAWINGTOOLS_CURVE5    32780
#define ID_TOOLS_DRAWINGTOOLS_CURVE6    32781
#define ID_TOOLS_DRAWINGTOOLS_CURVE7    32782
#define ID_TOOLS_DRAWINGTOOLS_CURVE8    32783
#define ID_TOOLS_DRAWINGTOOLS_GENIE     32784
#define ID_TOOLS_OPTIONS                32785
#define ID_HELP_ICOMAPHELP              32788
#define ID_HELP_ABOUTICOMAP             32789
#define ID_DRAWINGTOOL_LINE             32792
#define ID_DRAWINGTOOL_LINE_ANGLE       32793
#define ID_DRAWINGTOOL_CURVE1           32794
#define ID_DRAWINGTOOL_CURVE2           32795
#define ID_DRAWINGTOOL_CURVE3           32796
#define ID_DRAWINGTOOL_CURVE4           32797
#define ID_DRAWINGTOOL_CURVE5           32798
#define ID_DRAWINGTOOL_CURVE6           32799
#define ID_DRAWINGTOOL_CURVE7           32800
#define ID_DRAWINGTOOL_CURVE8           32801
#define ID_DRAWINGTOOL_GENIE            32802
#define ID_SKETCHTOOL_FINISHSKETCH      32803
#define ID_SKETCHTOOL_DELETESKETCH      32804
#define ID_SKETCHTOOL_FINISHPART        32805
#define ID_CURVEOPERATIONS_CURVEDIRECTION_CONCAVELEFT 32809
#define ID_CURVEOPERATIONS_CURVEDIRECTION_CONCAVERIGHT 32810
#define ID_CURVEOPERATIONS_DELTAANGLE_GREATERTHAN180 32811
#define ID_CURVEOPERATIONS_DELTAANGLE_LESSTHAN180 32812
#define ID_CURVEOPERATIONS_CONFIRMCURVE 32813
#define ID_TOOLS_SELECTFEATURES         32814
#define ID_TOOLS_DRAWINGDIRECTION_NORMAL 32816
#define ID_TOOLS_DRAWINGDIRECTION_REVERSE 32817
#define ID_TOOLS_ACTIONS_FINISHSKETCH   32819
#define IDC_BTN_ViewEditAttributes      32820
#define ID_TOOLS_EDITFEATURES           32821
#define IDC_BTN_FinishPart              32822
#define IDC_BTN_DeleteSketch            32823
#define IDC_BTN_FinishSketch            32824
#define ID_COPY                         32825
#define ID_SELECT_ALL                   32827
#define ID_CLEAR_ALL                    32828
#define ID_DELETE_SELECTED              32830
#define ID_LINE                         32832
#define ID_LINE_ANGLE                   32835
#define ID_CURVE1                       32836
#define ID_CURVE2                       32837
#define ID_CURVE3                       32838
#define ID_CURVE4                       32839
#define ID_CURVE5                       32840
#define ID_CURVE6                       32841
#define ID_CURVE7                       32842
#define ID_CURVE8                       32843
#define ID_GENIE                        32844
#define ID_REVERSE                      32845
#define ID_RIGHT                        32846
#define ID_GT180                        32847
#define ID_TOOLS_OCRSCHEMES             32848
#define ID_VIEW_DIG                     32851
#define ID_VIEW_STATUS                  32852
#define IDC_BTN_DIG                     32853
#define ID_DIG_INSERT_DUPLICATE         32854
#define ID_DIG_REMOVE                   32855
#define ID_DIG_UP                       32856
#define ID_DIG_DOWN                     32857
#define IDC_STATUS_BAR                  57603
#define IDS_SIZE                        61440
#define IDS_MOVE                        61456
#define IDS_MINIMIZE                    61472
#define IDS_MAXIMIZE                    61488
#define IDS_CLOSE                       61536
#define IDS_RESTORE                     61728

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        334
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         334
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
