//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AFValueModifiers.rc
//
#define IDS_PROJNAME                    100
#define IDR_LIMITASLEFTPART             102
#define IDR_LIMITASRIGHTPART            103
#define IDR_LIMITASMIDPART              104
#define IDS_TITLELimitAsLeftPartPP      106
#define IDS_HELPFILELimitAsLeftPartPP   107
#define IDS_DOCSTRINGLimitAsLeftPartPP  108
#define IDR_LIMITASLEFTPARTPP           109
#define IDD_LIMITASLEFTPARTPP           110
#define IDR_TRANSLATEVALUE              111
#define IDR_REMOVECHARACTERS            112
#define IDR_REPLACESTRINGS              113
#define IDR_TRANSLATETOCLOSESTVALUEINLIST 114
#define IDS_TITLELimitAsMidPartPP       115
#define IDS_HELPFILELimitAsMidPartPP    116
#define IDS_DOCSTRINGLimitAsMidPartPP   117
#define IDR_LIMITASMIDPARTPP            118
#define IDD_LIMITASMIDPARTPP            119
#define IDS_TITLELimitAsRightPartPP     120
#define IDS_HELPFILELimitAsRightPartPP  121
#define IDS_DOCSTRINGLimitAsRightPartPP 122
#define IDR_LIMITASRIGHTPARTPP          123
#define IDD_LIMITASRIGHTPARTPP          124
#define IDS_TITLERemoveCharactersPP     130
#define IDS_HELPFILERemoveCharactersPP  131
#define IDS_DOCSTRINGRemoveCharactersPP 132
#define IDR_REMOVECHARACTERSPP          133
#define IDD_REMOVECHARACTERSPP          134
#define IDS_TITLEReplaceStringsPP       135
#define IDS_HELPFILEReplaceStringsPP    136
#define IDS_DOCSTRINGReplaceStringsPP   137
#define IDR_REPLACESTRINGSPP            138
#define IDD_REPLACESTRINGSPP            139
#define IDS_TITLETranslateValuePP       140
#define IDS_HELPFILETranslateValuePP    141
#define IDS_DOCSTRINGTranslateValuePP   142
#define IDR_TRANSLATEVALUEPP            143
#define IDD_TRANSLATEVALUEPP            144
#define IDS_TITLETranslateToClosestValueInListPP 145
#define IDS_HELPFILETranslateToClosestValueInListPP 146
#define IDS_DOCSTRINGTranslateToClosestValueInListPP 147
#define IDR_TRANSLATETOCLOSESTVALUEINLISTPP 148
#define IDD_TRANSLATETOCLOSESTVALUEINLISTPP 149
#define IDR_ADVANCEDREPLACESTRING       150
#define IDS_TITLEAdvancedReplaceStringPP 151
#define IDS_HELPFILEAdvancedReplaceStringPP 152
#define IDS_DOCSTRINGAdvancedReplaceStringPP 153
#define IDR_ADVANCEDREPLACESTRINGPP     154
#define IDD_ADVANCEDREPLACESTRINGPP     155
#define IDR_INSERTCHARACTERS            156
#define IDS_TITLEInsertCharactersPP     157
#define IDS_HELPFILEInsertCharactersPP  158
#define IDS_DOCSTRINGInsertCharactersPP 159
#define IDR_INSERTCHARACTERSPP          160
#define IDD_INSERTCHARACTERSPP          161
#define IDR_STRINGTOKENIZERMODIFIER     162
#define IDS_TITLEStringTokenizerModifierPP 163
#define IDS_HELPFILEStringTokenizerModifierPP 164
#define IDS_DOCSTRINGStringTokenizerModifierPP 165
#define IDR_STRINGTOKENIZERMODIFIERPP   166
#define IDD_STRINGTOKENIZERMODIFIERPP   167
#define IDR_CHANGECASE                  168
#define IDR_CHANGECASEPP                169
#define IDD_CHANGECASEPP                170
#define IDS_TITLEChangeCasePP           171
#define IDS_HELPFILEChangeCasePP        172
#define IDS_DOCSTRINGChangeCasePP       173
#define IDR_PADVALUE                    174
#define IDS_TITLEPadValuePP             175
#define IDS_HELPFILEPadValuePP          176
#define IDS_DOCSTRINGPadValuePP         177
#define IDR_PADVALUEPP                  178
#define IDD_PADVALUEPP                  179
#define IDR_CONDITIONALATTRIBUTEMODIFIER 180
#define IDD_PROPPAGE_OCRAREA            181
#define IDR_OCRAREA                     182
#define IDR_PROPPAGE_OCRAREA            183
#define IDR_SPLITREGIONINTOCONTENTAREAS 184
#define IDR_SPLITREGIONINTOCONTENTAREASPP 185
#define IDC_EDIT_NUM_OF_CHARS           201
#define IDD_DLG_SELECT_FILE             201
#define IDC_EDIT_NUM_OF_CHARS_LEFT      201
#define IDC_CHK_ACCEPT_LESS             202
#define IDC_CHK_ACCEPT_LEFT             202
#define IDI_ICON_UP                     202
#define IDC_EDIT_START_POS              203
#define IDI_ICON_DOWN                   203
#define IDC_EDIT_END_POS                205
#define IDI_ICON_INFO                   205
#define IDC_EDIT1                       206
#define IDC_EDIT_NUM_OF_CHARS_RIGHT     206
#define IDC_EDIT_OTHER_CHARS            206
#define IDC_EDIT_POSITION               206
#define IDC_EDIT_TO_BE_REPLACED         206
#define IDC_EDIT_TEXT_IN_BETWEEN        206
#define IDC_EDIT_PADDING_CHARACTER      206
#define IDC_CHK_ACCEPT_RIGHT            207
#define IDD_CHANGECASE                  207
#define IDI_ICON_SELECT_DOC_TAG         208
#define IDC_LIST_TRANS_VALUE            212
#define IDC_BTN_ADD                     213
#define IDC_BTN_REMOVE                  214
#define IDC_BTN_MODIFY                  215
#define IDC_BTN_LOAD_FROM_FILE          216
#define IDC_BTN_SAVE_TO_FILE            217
#define IDC_EDIT_FILENAME               219
#define IDC_BTN_REMOVE2                 220
#define IDC_EDIT_DELIMITER              221
#define IDC_CHK_CASE1                   222
#define IDC_LIST_REPLACE_STRING         223
#define IDC_BTN_ADD2                    224
#define IDC_BTN_BROWSE                  225		// to match Utils project
#define IDC_BTN_MODIFY2                 226
#define IDC_BTN_LOADFILE2               227
#define IDC_CHK_CASE2                   228
#define IDC_LIST_VALUE_LIST             229
#define IDC_BTN_ADD_VALUE               230
#define IDC_BTN_REMOVE_VALUE            231
#define IDC_BTN_MODIFY_VALUE            232
#define IDC_BTN_LOAD_FILE_VALUES        233
#define IDC_CHK_CASE3                   234
#define IDC_STATIC_DELIMITER            235
#define IDC_BTN_SAVE_FILE_VALUES        236
#define IDC_RADIO_SELECT_FOLLOW         237
#define IDC_CHK_SPACE                   238
#define IDC_CHK_TAB                     239
#define IDC_CHK_RETURN                  240
#define IDC_CHK_OTHER_CHARS             241
#define IDC_CHK_CASE4                   242
#define IDC_CHK_ACCEPT_SHORTER_MID      243
#define IDC_CHK_CONSOLIDATE             244
#define IDC_CHK_TRIM_LEADING            245
#define IDC_CHK_TRIM_TRAILING           246
#define IDC_BTN_UP                      247
#define IDC_BTN_DOWN                    248
#define IDC_CHK_AS_REGEXP               249
#define IDC_RADIO_APPEND                250
#define IDC_RADIO_SPECIFIED             251
#define IDC_EDIT_CHAR_INSERT            252
#define IDC_BTN_SELECT_FIND_DOC_TAG     253
#define IDC_CMB_LENGTH_TYPE             254
#define IDC_BTN_SELECT_REPLACE_DOC_TAG  255
#define IDC_EDIT_REPLACEMENT            256
#define IDC_RADIO_ALL                   257
#define IDC_RADIO_FIRST                 258
#define IDC_RADIO_LAST                  259
#define IDC_CHK_CASE_ARS                260
#define IDC_CHK_AS_REG_EXPR_ARS         261
#define IDC_EDIT_SPECIFIED_OCC          262
#define IDC_RADIO_EXTRACT               263
#define IDC_RADIO_REMOVE                264
#define IDC_EDIT_RESULT                 265
#define IDC_CMB_NUM_OF_TOKENS_TYPE      266
#define IDC_EDIT_NUM_OF_TOKENS          267
#define IDC_CHK_FORCE                   268
#define IDC_RADIO_REMOVE_ALL            269
#define IDC_POSITION_INFO               270
#define IDC_EXPR_INFO                   271
#define IDC_BTN_SAVEFILE2               272
#define IDC_RADIO_NOCHANGE              273
#define IDC_RADIO_UPPERCASE             274
#define IDC_RADIO_LOWERCASE             275
#define IDC_RADIO_TITLECASE             276
#define IDC_CONSOLIDATE_INFO            277
#define IDC_RADIO_TRANSLATE_VALUE       278
#define IDC_RADIO_TRANSLATE_TYPE        279
#define IDC_RADIO_PADLEFT               280
#define IDC_RADIO_PADRIGHT              281
#define IDC_EDIT_REQUIRED_LENGTH        282
#define IDC_CLUE_DYNAMIC_LIST_HELP      283
#define IDC_DYNAMIC_FIND_HELP           284
#define IDC_DYNAMIC_REPLACE_HELP        285
#define IDC_BTN_BROWSE_FIND_FILE        286
#define IDC_BTN_BROWSE_REPLACE_FILE     287
#define IDI_ICON_DYNAMIC_LIST           288
#define IDC_OCRAREA_CHECK_ALPHA         289
#define IDC_OCRAREA_CHECK_DIGIT         290
#define IDC_OCRAREA_CHECK_PERIOD        291
#define IDC_OCRAREA_CHECK_HYPHEN        292
#define IDC_OCRAREA_CHECK_UNDERSCORE    293
#define IDC_OCRAREA_CHECK_COMMA         294
#define IDC_OCRAREA_EDIT_CUSTOM_CHARS   295
#define IDC_OCRAREA_CHECK_FORWARD_SLASH 296
#define IDC_OCRAREA_CHECK_UNRECOGNIZED  297
#define IDC_OCRAREA_CHECK_CUSTOM        298
#define IDC_OCRAREA_RADIO_PRINTED       299
#define IDC_OCRAREA_RADIO_HANDWRITING   300
#define IDC_OCRAREA_RADIO_CLEAR_IF_NONE_FOUND 301
#define IDC_OCRAREA_RADIO_RETAIN_IF_NONE_FOUND 302
#define IDD_SPLITREGIONPP               303
#define IDD_SPLITREGIONINTOCONTENTAREASPP 304
#define IDC_EDIT_DEFAULT_TEXT           305
#define IDC_EDIT_MINIMUM_WIDTH          306
#define IDC_EDIT_MINIMUM_HEIGHT         307
#define IDC_CHECK_INCLUDE_GOOD_OCR      308
#define IDC_CHECK_INCLUDE_POOR_OCR      309
#define IDC_EDIT_GOOD_OCR_TYPE          310
#define IDC_EDIT_POOR_OCR_TYPE          311
#define IDC_EDIT_OCR_THRESHOLD          312
#define IDC_CHECK_RE_OCR                313
#define IDC_CHECK_USE_LINES             314
#define IDC_EDIT_SUBATTRIBUTE_NAME      315
#define IDC_CHECK_OCR_AS_SUBATTRIBUTE   316
#define IDC_EDIT_REQD_HORZ_SEPARATION   317

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         318
#define _APS_NEXT_SYMED_VALUE           186
#endif
#endif
