//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AFCore.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_PROJNAME                    100
#define IDD_ABOUTBOX                    101
#define IDS_ABOUTBOX                    102
#define IDR_IVALUEFINDINGRULE           104
#define IDR_ATTRIBUTERULE               105
#define IDR_RULESET                     106
#define IDR_ATTRIBUTE                   108
#define IDR_RSEDITOR                    109
#define IDR_ATTRIBUTEFINDERENGINE       110
#define IDR_ATTRIBUTEFINDINFO           111
#define IDR_AFDOCUMENT                  112
#define IDR_RULEEXECUTIONENV            113
#define IDR_RULEEXECUTIONSESSION        114
#define IDR_FEEDBACKMGRINTERNALS        115
#define IDR_RULETESTERUI                116
#define IDS_TITLETesterDlgRulesetPage   118
#define IDS_HELPFILETesterDlgRulesetPage 119
#define IDS_DOCSTRINGTesterDlgRulesetPage 120
#define IDR_TESTERDLGRULESETPAGE        121
#define IDD_TESTERDLG_RULESET_PAGE      122
#define IDS_TITLEAttributeFinderEnginePP 123
#define IDS_HELPFILEAttributeFinderEnginePP 124
#define IDS_DOCSTRINGAttributeFinderEnginePP 125
#define IDR_ATTRIBUTEFINDERENGINEPP     126
#define IDD_ATTRIBUTEFINDERENGINEPP     127
#define IDS_TITLEConditionalRulePP      128
#define IDS_HELPFILEConditionalRulePP   129
#define IDS_DOCSTRINGConditionalRulePP  130
#define IDR_CONDITIONALRULEPP           131
#define IDD_CONDITIONALRULEPP           132
#define IDR_SPATIALLYCOMPAREATTRIBUTES  133
#define IDD_DLG_EDITOR                  201
#define IDC_COMBO_ATTRIBUTES            202
#define IDR_MNU_EDITOR                  203
#define IDC_BTN_ADDATTR                 204
#define IDC_BTN_DELATTR                 205
#define IDD_DLG_SELECTIV                206
#define IDC_BTN_RENATTR                 207
#define IDD_DLG_ADDRULE                 208
#define IDC_BTN_ADDRULE                 209
#define IDD_DLG_TESTER                  210
#define IDC_LIST_RULES                  211
#define IDR_TESTERDLG_TOOLBAR           212
#define IDC_BTN_DELRULE                 213
#define IDC_BTN_CONRULE                 214
#define IDD_DLG_IMPORT_ATTRIBUTES       215
#define IDR_ACCELERATOR_TESTERDLG       216
#define IDI_ICON_DOC                    217
#define IDC_BTN_RULEUP                  218
#define IDC_BTN_RULEDOWN                219
#define IDR_ACCELERATOR_EDITORDLG       220
#define IDC_CHECK_STOP                  221
#define IDC_LIST_IGNORE                 222
#define IDD_TESTERDLG_SETTINGS_PAGE     223
#define IDD_ENGINE_PROGRESS_DLG         224
#define IDC_BTN_ADDIGNORE               225
#define IDD_TESTERDLG_INPUT_PAGE        226
#define IDB_BITMAP_PROGRESS_FRAME1      227
#define IDD_TESTERDLG_OUTPUTHANDLERS_PAGE 228
#define IDC_BTN_DELIGNORE               229
#define IDC_BTN_RENIGNORE               230
#define IDI_ICON_DOWN                   231
#define IDC_CHECK_IV                    232
#define IDI_ICON_UP                     233
#define IDC_EDIT_IV                     234
#define IDR_MNU_CONTEXT                 235
#define IDC_EDIT_OH                     235
#define IDC_BTN_SELECTIV                236
#define IDC_COMBO_IV                    237
#define IDC_BTN_SELECTOH                237
#define IDC_EDIT_DESC                   238
#define IDC_EDIT_ATTRIBUTE_SPLITTER     239
#define IDC_PROPERTIES                  240
#define IDC_BTN_SELECT_ATTRIBUTE_SPLITTER 241
#define IDC_COMBO_RULE                  242
#define IDC_BTN_CONFIG_RULE             242
#define IDC_STATIC_DESC                 243
#define IDC_CHECK_MODIFY                244
#define IDC_BTN_CONRULE2                245
#define IDC_STATIC_SELECT               246
#define IDC_BTN_CONFIGURE               247
#define IDC_STATIC_SCOPE                248
#define IDC_RADIO_ALL                   249
#define IDC_RADIO_CURRENT               250
#define IDC_STATIC_INPUT                251
#define IDC_COMBO_INPUT                 252
#define ID_TEST                         253
#define IDC_EDIT_TESTINPUT              254
#define ID_CLEAR                        255
#define IDC_LIST_RESULTS                256
#define IDC_STATIC_RESULTS              257
#define IDC_PROGRESS_ATTR               258
#define ID_BROWSE                       259
#define IDC_STATIC_ATTRIBUTE_NAME       260
#define IDC_STATIC_RULE_DESCRIPTION     261
#define IDC_PROGRESS_RULE               262
#define IDC_STATIC_ANIMATION            263
#define IDR_PROGRESS_ANIMATION          264
#define IDC_EDIT_FILE                   265
#define IDC_STATIC_CONFIGURE            266
#define IDB_BUTTON_UP                   267
#define IDB_BUTTON_DOWN                 268
#define IDC_CHECK_SHOW_VALID            269
#define IDC_GRID                        270
#define IDC_PICTURE                     271
#define IDC_LIST1                       272
#define IDC_COUNTER_LIST                272
#define IDC_LIST_OUTPUTHANDLERS         273
#define IDC_SPLITTER                    274
#define IDC_STATIC_FILENAME             275
#define IDC_BTN_ADD                     276
#define IDC_BTN_REMOVE                  277
#define IDC_BTN_MODIFY                  278
#define IDC_BTN_UP                      279
#define IDC_BTN_DOWN                    280
#define IDC_CHK_IGNORE                  281
#define ID_CANCEL_SEARCH                282
#define IDC_EDIT_PREPROCESSOR           283
#define IDC_BTN_SELECTPP                284
#define IDI_ICON_RULE_TESTER            285
#define IDC_EDIT_PRD_VERSION            286
#define IDC_STATIC_PP                   287
#define IDC_STATIC_ATTR                 288
#define IDC_STATIC_RULES                289
#define IDC_STATIC_IV                   290
#define IDC_STATIC_SPLIT                291
#define IDC_STATIC_PROMPT               292
#define IDC_STATIC_OH                   293
#define IDC_RULESET                     294
#define IDC_STATIC_RULESET              295
#define IDC_EDIT_RULE_FILE              296
#define IDC_BTN_BROWSE_AFE              297
#define IDC_CHK_FROM_USS                298
#define IDC_CHK_CREATE_USS              299
#define IDC_BTN_BROWSE_RSD              300
#define IDC_TREE_LIST                   301
#define IDD_DLG_TESTER_EDIT             302
#define IDC_EDIT_NAME                   303
#define IDC_EDIT_VALUE                  304
#define IDC_EDIT_TYPE                   305
#define IDC_RADIO_OCR_ALL               306
#define IDC_RADIO_OCR_SPECIFIED         307
#define IDD_COUNTERS_DLG                308
#define IDD_RULESET_PROPERTIES_DLG      309
#define IDC_EDIT_PAGES                  310
#define IDC_CMB_CONDITION               311
#define IDC_CMB_RULE                    312
#define IDC_CMB_TRUE_FALSE              313
#define IDC_BTN_CONFIG_CONDITION        314
#define IDC_TEXT_MUST_CONFIG            315
#define IDC_EDIT_FKB_VERSION            316
#define IDC_CHECK_INTERNAL_USE_ONLY     317
#define IDC_SERIAL_NUMBERS              318
#define IDC_APPICON                     319
#define IDI_FLEX_DATA_ENTRY             320
#define IDI_ID_SHIELD                   321
#define IDC_CHECK_DOCUMENT_PP           323
#define IDC_CHECK_INPUT_VALIDATOR       324
#define IDC_CHECK_ATT_SPLITTER          325
#define IDC_CHECK_OUTPUT_HANDLER        326
#define IDC_CHECK_AFRULE_DOC_PP         327
#define IDC_CHECK_SWIPING_RULE          328
#define IDC_CHECK_PERFORM_OCR           329
#define IDC_FKB_VERSION                 330
#define IDC_CHECK_IGNORE_AS_ERRORS      331
#define IDC_CHECK_IGNORE_OH_ERRORS      332
#define IDC_CHECK_IGNORE_PP_ERRORS      333
#define IDC_CHECK_IGNORE_MODIFIER_ERRORS 334
#define ID_FILE_SAVEAS                  32768
#define ID_FILE_EXIT                    32769
#define ID_TOOLS_TEST                   32770
#define ID_TOOLS_CHECK                  32771
#define ID_HELP_ABOUT                   32772
#define ID_HELP_HELP                    32773
#define ID_BUTTON_SRIR                  32774
#define ID_BUTTON_HTIR                  32776
#define ID_FILE_IMPORT                  32777
#define ID_FILE_EXPORT                  32778
#define ID_BUTTON_EXECUTE               32779
#define ID_BUTTON_CLEAR                 32780

// Use resource value previously defined in BaseUtils
#define ID_EDIT_DELETE                  6023

#define ID_CANCEL                       32782
#define ID_EDIT_DUPLICATE               32783
#define ID_TOOLS_HARNESS                32784
#define ID_BUTTON_VOA                   32785
#define ID_BUTTON_FEEDBACK              32786
#define ID_FILE_MRU                     32787
#define ID_MRU_FILE1                    32788
#define ID_MRU_FILE2                    32789
#define ID_MRU_FILE3                    32790
#define ID_MRU_FILE4                    32791
#define ID_MRU_FILE5                    32792
#define ID_FILE_COUNTERS                32796
#define ID_FILE_PROPERTIES              32797
#define ID_BUTTON_KEY_SR                32798
#define ID_BUTTON_ABOUT                 32799
#define ID_INDICATOR_COUNTERS           57604
#define ID_INDICATOR_INTERNAL_USE_ONLY  57605
#define ID_INDICATOR_SERIAL_NUMBERS     57606
#define IDS_FLEXINDEX_PRODUCT           57607
#define IDS_IDSHIELD_PRODUCT            57608
#define IDS_UNKNOWN_PRODUCT             57609
#define IDS_RULETESTER_PRODUCT          57610

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        309
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         335
#define _APS_NEXT_SYMED_VALUE           134
#endif
#endif
