#if !defined(AFX_IUNKNOWNVECTOR_H__DEC19BCA_B725_4644_9D71_55B5459555F0__INCLUDED_)
#define AFX_IUNKNOWNVECTOR_H__DEC19BCA_B725_4644_9D71_55B5459555F0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIUnknownVector wrapper class

class CIUnknownVector : public COleDispatchDriver
{
public:
	CIUnknownVector() {}		// Calls COleDispatchDriver default constructor
	CIUnknownVector(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CIUnknownVector(const CIUnknownVector& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	LPUNKNOWN Clone();
	void CopyFrom(LPUNKNOWN pObject);
	long Size();
	LPUNKNOWN At(long lPos);
	void PushBack(LPUNKNOWN pObj);
	void Clear();
	LPUNKNOWN Front();
	LPUNKNOWN Back();
	void PopBack();
	void Remove(long nIndex);
	void Append(LPDISPATCH pVector);
	void Insert(long lPos, LPUNKNOWN pObj);
	void Set(long lPos, LPUNKNOWN pObj);
	void Swap(long lPos1, long lPos2);
	BOOL IsOrderFreeEqualTo(LPDISPATCH pVector);
	long FindByValue(LPUNKNOWN pObj, long nStartIndex);
	void InsertVector(long lPos, LPDISPATCH pObj);
	void RemoveRange(long nStart, long nEnd);
	void LoadFrom(LPCTSTR strFullFileName, BOOL bSetDirtyFlagToTrue);
	void SaveTo(LPCTSTR strFullFileName, BOOL bClearDirty);
	void RemoveValue(LPUNKNOWN pObj);
	LPDISPATCH At2(long lPos);
	void PushBackIfNotContained(LPUNKNOWN pObj);
	void FindByReference(LPUNKNOWN pObj, long nStartPos, long* pRetVal);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IUNKNOWNVECTOR_H__DEC19BCA_B725_4644_9D71_55B5459555F0__INCLUDED_)
