#if !defined(AFX_OCRFILTERMGR_H__2CB7BD63_6209_4FF2_8FF0_91795353A22A__INCLUDED_)
#define AFX_OCRFILTERMGR_H__2CB7BD63_6209_4FF2_8FF0_91795353A22A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COCRFilterMgr wrapper class

class COCRFilterMgr : public COleDispatchDriver
{
public:
	COCRFilterMgr() {}		// Calls COleDispatchDriver default constructor
	COCRFilterMgr(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	COCRFilterMgr(const COCRFilterMgr& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetCurrentScheme();
	void SetCurrentScheme(LPCTSTR strSchemeName);
	void ShowFilterSchemesDlg();
	void ShowFilterSettingsDlg();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OCRFILTERMGR_H__2CB7BD63_6209_4FF2_8FF0_91795353A22A__INCLUDED_)
