// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ocrfiltermgr.h"


/////////////////////////////////////////////////////////////////////////////
// COCRFilterMgr properties

/////////////////////////////////////////////////////////////////////////////
// COCRFilterMgr operations

CString COCRFilterMgr::GetCurrentScheme()
{
	CString result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void COCRFilterMgr::SetCurrentScheme(LPCTSTR strSchemeName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strSchemeName);
}

void COCRFilterMgr::ShowFilterSchemesDlg()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void COCRFilterMgr::ShowFilterSettingsDlg()
{
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
