Columns:
  - Date
  - Testing Set
  - Attribute Name
  - '# Attributes'
  - '# Attributes Match'
  - % Attributes Match
  - Incorrectly Found
  - ROCE
  - '# Docs'
  - '# Docs Match'
  - % Docs Match
  - Tester
  - Notes
SummaryColumns:
  - '# Attributes'
  - '# Attributes Match'
  - Incorrectly Found
ComputedColumns:
  % Attributes Match: '=IF(AND(E#<>"",D#<>"",D#<>0),E#/D#,"")'
  ROCE: '=IF(AND(G#<>"",G#<>0,E#<>""),E#/G#,"NaN")'
FixedColumns:
  Tester: NH
  Notes: 'None'
  Testing Set: 'Set003'
GlobalComputedColumns:
  % Docs Match: '=IF(AND(J#<>"",I#<>"",I#<>0),J#/I#,"")'
ColumnsFromXML:
  Global:
    Date:
      Node: //Summary/ID
      Pattern: .+
    '# Docs':
      Node: //Summary/Line[0]
      Pattern: \d+
    '# Docs Match':
      Node: //Summary/Line[1]
      Pattern: \d+
  Row:
    Node: //TestCaseDetailNote
    Columns:
      Attribute Name:
          Node: Title
          Pattern: \w+$
          Skip: ^Test$|Min$|Max$|Info$|Address$
      '# Attributes':
          Node: Detail/Line[0]
          Pattern: \d+
      '# Attributes Match':
          Node: Detail/Line[1]
          Pattern: \d+
      'Incorrectly Found':
          Node: Detail/Line[2]
          Pattern: \d+
