IF "%~1"=="" GOTO missing_version_number_error

GOTO create_images

:missing_version_number_error
ECHO.
ECHO ***** ERROR *****
ECHO Please provide version number of product to build as the first argument!
ECHO.
GOTO exit_script

:create_images

SET FLEX_VERSION=%~1
SET FLEX_VERSION_NUM=%FLEX_VERSION:FlexIndex Ver. =_%
SET FLEX_VERSION_STRING=%FLEX_VERSION_NUM:.=_%

"C:\Program Files (x86)\ImgBurn\ImgBurn.exe" /MODE BUILD /NOIMAGEDETAILS /BUILDOUTPUTMODE IMAGEFILE /SRC "M:\ISOTree\%FLEX_VERSION%\FLEXIndex\FlexIndex\" /DEST "M:\ISOTree\%FLEX_VERSION%\FLEXIndex\ISO\Flex%FLEX_VERSION_STRING%.iso" /FILESYSTEM "ISO9660 + UDF" /VOLUMELABEL_ISO9660 "Flex%FLEX_VERSION_STRING%" /VOLUMELABEL_UDF "Flex%FLEX_VERSION_STRING%" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE


"C:\Program Files (x86)\ImgBurn\ImgBurn.exe" /MODE BUILD /NOIMAGEDETAILS /BUILDOUTPUTMODE IMAGEFILE /SRC "M:\ISOTree\%FLEX_VERSION%\FLEXIndex\FlexIndexExtras\" /DEST "M:\ISOTree\%FLEX_VERSION%\FLEXIndex\ISO\FlexExtras%FLEX_VERSION_STRING%.iso" /FILESYSTEM "ISO9660 + UDF" /VOLUMELABEL_ISO9660 "FlexExtras%FLEX_VERSION_STRING%" /VOLUMELABEL_UDF "FlexExtras%FLEX_VERSION_STRING%" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE


"C:\Program Files (x86)\ImgBurn\ImgBurn.exe" /MODE BUILD /NOIMAGEDETAILS /BUILDOUTPUTMODE IMAGEFILE /SRC "M:\ISOTree\%FLEX_VERSION%\IDShield\IDShield\" /DEST "M:\ISOTree\%FLEX_VERSION%\IDShield\ISO\IDShield%FLEX_VERSION_STRING%.iso" /FILESYSTEM "ISO9660 + UDF" /VOLUMELABEL_ISO9660 "IDShield%FLEX_VERSION_STRING%" /VOLUMELABEL_UDF "IDShield%FLEX_VERSION_STRING%" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE


"C:\Program Files (x86)\ImgBurn\ImgBurn.exe" /MODE BUILD /NOIMAGEDETAILS /BUILDOUTPUTMODE IMAGEFILE /SRC "M:\ISOTree\%FLEX_VERSION%\IDShield\IDShieldExtras\" /DEST "M:\ISOTree\%FLEX_VERSION%\IDShield\ISO\IDShieldExtras%FLEX_VERSION_STRING%.iso" /FILESYSTEM "ISO9660 + UDF" /VOLUMELABEL_ISO9660 "IDShieldExtras%FLEX_VERSION_STRING%" /VOLUMELABEL_UDF "IDShieldExtras%FLEX_VERSION_STRING%" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE

"C:\Program Files (x86)\ImgBurn\ImgBurn.exe" /MODE BUILD /NOIMAGEDETAILS /BUILDOUTPUTMODE IMAGEFILE /SRC "M:\ISOTree\%FLEX_VERSION%\LabDE\LabDE\" /DEST "M:\ISOTree\%FLEX_VERSION%\LabDE\ISO\LabDE%FLEX_VERSION_STRING%.iso" /FILESYSTEM "ISO9660 + UDF" /VOLUMELABEL_ISO9660 "LabDE%FLEX_VERSION_STRING%" /VOLUMELABEL_UDF "LabDE%FLEX_VERSION_STRING%" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE


"C:\Program Files (x86)\ImgBurn\ImgBurn.exe" /MODE BUILD /NOIMAGEDETAILS /BUILDOUTPUTMODE IMAGEFILE /SRC "M:\ISOTree\%FLEX_VERSION%\LabDE\LabDEExtras\" /DEST "M:\ISOTree\%FLEX_VERSION%\LabDE\ISO\LabDEExtras%FLEX_VERSION_STRING%.iso" /FILESYSTEM "ISO9660 + UDF" /VOLUMELABEL_ISO9660 "LabDEExtras%FLEX_VERSION_STRING%" /VOLUMELABEL_UDF "LabDEExtras%FLEX_VERSION_STRING%" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE


:exit_script