;;; This script requires AutoHotKey available at http://www.autohotkey.com/
;;; 
;;; Turn on ScrollLock to pause the script (it will finish the current image first)

SetTitleMatchMode, 2
DetectHiddenText, on

; Text to search for in LabDE window title. This is a part of the image file name. eg. "350_x.tif" where
; 'x' is a number generated by CopyNumberedFiles.exe
LabDEWindowTitle := "350_"	

; Default time in milliseconds to wait for lag between mouse clicks/text entry
SleepTime := 500

Loop,
{
	;pause script if scroll lock is on
	Gosub, PauseIfScrollLock
	
	;Resize LabDE window
		WinWait, LabDE,
		IfWinNotActive, LabDE,,
			WinActivate, LabDE,
		Winmove, LabDE, , 1, 1, 1000, 600

	;; Wait for an image to be loaded for verification
	WinWait, % LabDEWindowTitle,
	IfWinNotActive, % LabDEWindowTitle, ,
		WinActivate, % LabDEWindowTitle,
	;;WinWaitActive, % LabDEWindowTitle,
	Sleep, SleepTime

	;Press "Copy" button
	MouseClick, left,  531,  201
	Sleep, 2000
	MouseClick, left,  531,  201
	Sleep, SleepTime
	
	; Select name row From EpicCare:
	MouseClick, left, 35, 350, 1	
	clipboard=LAUX, NEAL M 
	Sleep, SleepTime
	; Paste
	Send ^v
	Sleep, SleepTime
	
	;;Type in MR number
	; Select MR # edit box
	Send, {Tab 3}
	Sleep, SleepTime
	Send, M123456
	Sleep, SleepTime

	;;Enter ordering physician code
	Send, {Tab}{Right 3}
	Sleep, SleepTime
	Send, 3085
	Sleep, SleepTime

	;;Edit a table cell and use shift+tab to exit edit mode
	Send, {TAB 2}
	Sleep, SleepTime
	Send, 1/01/2010
	Sleep, SleepTime
	Send, +{Space}
	Sleep, SleepTime
	
	;;Copy three test rows
	Send, {TAB 7}
	Sleep, SleepTime
	Send, +{Down}+{Down}
	Sleep, SleepTime
	Send, ^x
	Sleep, SleepTime
	Sleep, SleepTime
	Sleep, SleepTime
	
	;;Paste them into the other order
	Send, {F3}
	Sleep, SleepTime
	Send, {Tab 6}{Down}
	Sleep, SleepTime
	Send, ^v
	Sleep, SleepTime

	;;Paste them into the other order
	MouseClick, right,  35,  341
	Sleep, SleepTime
	Send, {Down 7}{Enter}
	Sleep, SleepTime
	
	;; Correct the name of one of the tests
	Send, ast{Space}{Tab}
	Sleep, SleepTime
	
	;; Go back to the order table
	Send, ^{Down}
	Sleep, SleepTime
	Send, {Tab}{F3}

	;; Create a new order
	Send, {Home}
	Sleep, SleepTime
	Send, ^{Down}
	Sleep, SleepTime
	Send, CBC{Tab}
	Sleep, SleepTime
	
	;; Delete all orders
	Send, ^a
	Send, {DELETE}
	Sleep, SleepTime

	;;Swipe in order
	; Set image window to show entire page
	Send !p
	Sleep, SleepTime
	; Select the rectangular swipe tool
	Send, {Alt}
	Sleep, SleepTime
	Send t
	Sleep, SleepTime
	Send s
	Sleep, SleepTime
	;MouseClick, left, 625, 237, , , d
	MouseClick, left, 620, 180, , , d	;swipe bigger box in order to get Collection Date/Time
	Sleep, SleepTime
	MouseClick, left, 916, 280, , , u
	Sleep, 15000

	; Select Order Number edit box
	Send, {Tab}
	Sleep, SleepTime
	; input valid data
	Send, 123456
	Sleep, SleepTime
	
	; Select Result Date edit box
	Send, {Tab}
	Sleep, SleepTime
	; input a valid date
	Send, 01/01/1901
	Sleep, SleepTime

	; Select Result Time edit box
	Send, {Tab}
	Sleep, SleepTime
	; input a valid time
	Send, 12:00
	Sleep, SleepTime
	
	; Select Lab Code edit box
	Send, {Tab 2}
	Sleep, SleepTime
	Send {Space}{b}
	Sleep, SleepTime
	Send {Tab}
	Sleep, SleepTime

	; Enter a smart tag in the comment box
	Send, {End}{Enter}
	Send, .tz
	Sleep, SleepTime
	Send, {Backspace}est
	Sleep, SleepTime

	;; Toggle show all highlights
	Send, {F10}
	Sleep, SleepTime
	Send, {F10}
	Sleep, SleepTime

	;;Save
	ContinueToNextDocument()
}

;; Check for invalid data items. If F3 is pressed with no invalid data remaining, a message box is presented.
ContinueToNextDocument()
{
	Send {F3}
	Sleep, SleepTime
	; If invalid items remain do nothing.
	IfWinNotExist, LabDE, There are no invalid, ,
	{

		Send, {Enter}
		Sleep, SleepTime
		Send !f{Down 1}{Enter}
		Sleep, 2000
		Send !f{Down 3}{Enter}
	}
	else
	; Otherwise, hit ok on message box (press enter) and save the document.
	{
		Send, {Enter}
		Sleep, SleepTime
		Send ^s
	}

	Sleep, 2000
	Gosub, PauseIfScrollLock
}

PauseIfScrollLock:
    Loop
    {
		GetKeyState, lockstate, ScrollLock, T
		If lockstate = D
           Sleep, 1000
        Else
            break
    }
return