//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AFOutputHandlers.rc
//
#define IDC_SELECT_ALL                  3
#define IDC_CLEAR_ALL                   4
#define IDC_SELECT_VALID                5
#define IDS_PROJNAME                    100
#define IDR_ELIMINATEDUPLICATES         102
#define IDR_REMOVEINVALIDENTRIES        103
#define IDR_SELECTONLYUNIQUEVALUES      104
#define IDR_SELECTUSINGMAJORITY         105
#define IDR_SELECTWITHUI                106
#define IDR_OUTPUTHANDLERSEQUENCE       107
#define IDR_REMOVEENTRIESFROMLIST       108
#define IDR_KEEPATTRIBUTESINMEMORY      109
#define IDS_TITLERemoveEntriesFromListPP 110
#define IDS_HELPFILERemoveEntriesFromListPP 111
#define IDS_DOCSTRINGRemoveEntriesFromListPP 112
#define IDR_REMOVEENTRIESFROMLISTPP     113
#define IDD_REMOVEENTRIESFROMLISTPP     114
#define IDR_OUTPUTTOXML                 115
#define IDS_TITLEOutputToXMLPP          116
#define IDS_HELPFILEOutputToXMLPP       117
#define IDS_DOCSTRINGOutputToXMLPP      118
#define IDR_OUTPUTTOXMLPP               119
#define IDS_TITLEModifyAttributeValuePP 120
#define IDD_OUTPUTTOXMLPP               121
#define IDS_HELPFILEModifyAttributeValuePP 122
#define IDR_MODIFYATTRIBUTEVALUEOH      123
#define IDS_DOCSTRINGModifyAttributeValuePP 124
#define IDR_MODIFYATTRIBUTEVALUEPP      125
#define IDR_OUTPUTTOVOA                 126
#define IDS_TITLEOutputToVOAPP          127
#define IDS_HELPFILEOutputToVOAPP       128
#define IDS_DOCSTRINGOutputToVOAPP      129
#define IDR_OUTPUTTOVOAPP               130
#define IDD_OUTPUTTOVOAPP               131
#define IDR_MOVEANDMODIFYATTRIBUTES     132
#define IDS_TITLEMoveAndModifyAttributesPP 133
#define IDS_HELPFILEMoveAndModifyAttributesPP 134
#define IDS_DOCSTRINGMoveAndModifyAttributesPP 135
#define IDR_MOVEANDMODIFYATTRIBUTESPP   136
#define IDD_MOVEANDMODIFYATTRIBUTESPP   137
#define IDR_REMOVESUBATTRIBUTES         138
#define IDS_TITLERemoveSubAttributesPP  139
#define IDS_HELPFILERemoveSubAttributesPP 140
#define IDS_DOCSTRINGRemoveSubAttributesPP 141
#define IDR_REMOVESUBATTRIBUTESPP       142
#define IDD_REMOVESUBATTRIBUTESPP       143
#define IDR_REFORMATPERSONNAMES         144
#define IDS_TITLEReformatPersonNamesPP  145
#define IDS_HELPFILEReformatPersonNamesPP 146
#define IDS_DOCSTRINGReformatPersonNamesPP 147
#define IDR_REFORMATPERSONNAMESPP       148
#define IDD_REFORMATPERSONNAMESPP       149
#define IDR_RUNOBJECTONQUERY            150
#define IDS_TITLERunObjectOnQueryPP     151
#define IDS_HELPFILERunObjectOnQueryPP  152
#define IDS_DOCSTRINGRunObjectOnQueryPP 153
#define IDR_RUNOBJECTONQUERYPP          154
#define IDD_RUNOBJECTONQUERYPP          155
#define IDR_CONDITIONALOUTPUTHANDLER    156
#define IDR_MERGEATTRIBUTES             157
#define IDD_MERGEATTRIBUTESPP           158
#define IDR_MERGEATTRIBUTESPP           159
#define IDR_MERGEATTRIBUTETREES         160
#define IDD_MERGEATTRIBUTETREESPP       161
#define IDR_MERGEATTRIBUTETREESPP       162
#define IDD_MERGEATTRIBUTESPREFERENCELISTDLG 163
#define IDD_DLG_SelectWithUI            201
#define IDC_LIST_ENTRIES                202
#define IDD_MODIFYATTRIBUTEVALUE        203
#define IDC_CHK_CASE_SENSITIVE          204
#define IDC_BTN_ADD                     205
#define IDC_BTN_REMOVE                  206
#define IDC_BTN_MODIFY                  207
#define IDC_BTN_LOAD                    208
#define IDC_BTN_SAVE                    209
#define IDC_EDIT_ATTRIBUTENAME          210
#define IDC_EDIT_ATTRIBUTEQUERY         210
#define IDC_EDIT_ATTRIBUTEVALUE         211
#define IDC_CHECK_UPDATEVALUE           212
#define IDC_EDIT_ATTRIBUTETYPE          213
#define IDC_CHECK_UPDATETYPE            214
#define IDC_EDIT_QUERY                  214
#define IDC_EDIT_ATTRIBUTENAMECHANGE    215
#define IDC_RADIO_ROOT_NAME             216
#define IDC_CHECK_UPDATENAME            216
#define IDC_RADIO_SPECIFY_NAME          217
#define IDC_EDIT_SPECIFY_NAME           218
#define IDC_CHECK_ADD_ROOT_TYPE         222
#define IDC_EDIT_QUERY_PERSON_ATTRIBUTES 222
#define IDC_CHECK_ADD_SPECIFIED_TYPE    223
#define IDC_CHK_REFORMAT_SUB_NAMES      223
#define IDC_EDIT_SPECIFY_TYPE           224
#define IDC_EDIT_NAME_FORMAT            224
#define IDC_CHECK_DELETE_ROOT           225
#define IDC_RADIO_RETAIN_TYPE           226
#define IDC_CHECK_REMOVE_IF_SCORE       226
#define IDI_ICON_SELECT_DOC_TAG         226
#define IDC_RADIO_EMPTY_TYPE            227
#define IDC_RADIO_DO_NOT_CHANGE_NAME    228
#define IDC_COMBO_CONDITION             228
#define IDC_CHECK_ADD_NAME_TO_TYPE      229
#define IDC_EDIT_SCORE                  229
#define IDC_EDIT_DATA_SCORER_NAME       230
#define IDC_BUTTON_CHOOSE_DATA_SCORER   231
#define IDC_RADIO_MOVE_TO_ROOT          232
#define IDC_RADIO_MOVE_TO_PARENT        233
#define IDC_RADIO_MODIFY_SELECTED       235
#define IDC_RADIO_CREATE_SUB_ATTRIBUTE  236
#define IDC_CMB_OBJECT_TYPE             237
#define IDC_CMB_OBJECT                  238
#define IDC_BTN_CONFIGURE               239
#define IDC_TXT_MUST_CONFIGURE          240
#define IDC_RADIO_ORIGINAL              241
#define IDC_RADIO_SCHEMA                242
#define IDC_CHECK_NAMES                 243
#define IDC_CHECK_NAMES2                245
#define IDC_CHECK_SCHEMA                245
#define IDC_COMBO_ATTRIBUTE_SELECTOR    245
#define IDC_BUTTON1                     246
#define IDC_BUTTON_CONFIGURE_SELECTOR   246
#define IDC_BTN_SELECT_DOC_TAG          251
#define IDC_GRID                        260
#define IDC_PICTURE                     261
#define IDC_CLUE_DYNAMIC_LIST_HELP      283
#define IDC_BTN_BROWSE_FILE             303
#define IDC_NAME_FORMAT_INFO            303
#define IDC_EDIT_FILENAME               304
#define IDI_ICON_INFO                   305
#define IDC_EDIT_SCHEMANAME             305
#define IDR_CONDITIONALOUTPUTHANDER     306
#define IDI_ICON_UP                     307
#define IDI_ICON_DOWN                   308
#define IDC_EDIT_OVERLAP_PERCENT        309
#define IDC_EDIT_NAME                   310
#define IDC_RADIO_PRESERVE_NAME         311
#define IDC_RADIO_SPECIFY_TYPE          312
#define IDC_EDIT_TYPE                   313
#define IDC_RADIO_CREATE_MERGED_REGION  314
#define IDC_RADIO_COMBINE_TYPES         315
#define IDC_EDIT_VALUE                  316
#define IDC_CHECK_SUBATTRIBUTES         317
#define IDC_BTN_ADD_NAME                318
#define IDC_BTN_REMOVE_NAME             319
#define IDC_BTN_MODIFY_NAME             320
#define IDC_BTN_NAME_UP                 321
#define IDC_BTN_NAME_DOWN               322
#define IDC_LIST_NAMES                  323
#define IDC_CHK_XML_OUT_REMOVE_SPATIAL  324
#define IDC_EDIT_MERGE_TREES_QUERY      325
#define IDC_RADIO_MERGE_INTO_FIRST      326
#define IDC_RADIO_MERGE_INTO_BIGGEST    327
#define IDC_EDIT_MERGE_SUBATTRIBUTES    328
#define IDC_RADIO_NOMATCH_DISCARD       329
#define IDC_RADIO_NOMATCH_PRESERVE      330
#define IDC_CHECK_MERGE_CASESENSITIVE   331
#define IDC_CHECK_MERGE_COMPARE_TYPE    332
#define IDC_CHECK_MERGE_COMPARE_SUBATTR 333
#define IDC_CHECK_MERGE_REMOVE_EMPTY    334
#define IDC_MERGE_REMOVE_INFO           335
#define IDC_RADIO_MERGE_INDIVIDUAL_ZONES 336
#define IDD_MERGEATTRIBUTE_PRIORITYLIST_DLG 337
#define IDC_CHECK_REGEX                 338
#define IDC_RADIO_SELECT_TYPE           339
#define IDC_CHECK_TYPE_FROM_NAME        340
#define IDC_CHECK_PRESERVE_TYPE         341
#define IDC_RADIO_SPECIFY_VALUE         342
#define IDC_RADIO_SELECT_VALUE          343
#define IDC_RADIO_VALUE_FROM_NAME       344
#define IDC_BUTTON_EDIT_NAME_LIST       345
#define IDC_BUTTON_EDIT_TYPE_LIST       346
#define IDC_EDIT_NAME_LIST              347
#define IDC_EDIT_TYPE_LIST              348
#define IDC_EDIT_VALUE_LIST             349
#define IDC_BUTTON_EDIT_VALUE_LIST      350
#define IDC_RADIO_PRESERVE_VALUE        351

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        352
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         352
#define _APS_NEXT_SYMED_VALUE           164
#endif
#endif
